"HEROSK"
{
    "npc_dota_hero_abaddon"
	{
        "1"
        {
            "HasScepterAndShard"    "1"
            "1"		"abaddon_death_coil"
            "2"		"abaddon_aphotic_shield"
            "3"		"abaddon_frostmourne"
            "4"		"abaddon_font_of_avernus"
            "5"		"generic_hidden"
            "6"		"abaddon_borrowed_time"
            "10"		"special_bonus_unique_abaddon_6"
            "11"		"special_bonus_unique_abaddon_7"
            "12"		"special_bonus_unique_abaddon_5"
            "13"		"special_bonus_unique_abaddon_2"
            "14"		"special_bonus_unique_abaddon"
            "15"		"special_bonus_unique_abaddon_immolation"
            "16"		"special_bonus_unique_abaddon_3"
            "17"		"special_bonus_unique_abaddon_4"
        }
        "2"
        {
           
	
            "1"		"death_coil"
            "2"		"aphotic_shield"
            "3"		"frostmourne"
            "4"		"generic_hidden"
            "5"		"generic_hidden"
            "6"		"borrowed_time"
            "10"		"special_bonus_abaddon_1"
            "11"		"special_bonus_abaddon_2"
            "12"		"special_bonus_abaddon_3"
            "13"		"special_bonus_abaddon_4"
            "14"		"special_bonus_abaddon_5"
            "15"		"special_bonus_abaddon_6"
            "16"		"special_bonus_abaddon_7"
	        "17"		"special_bonus_abaddon_8"
	
        }
	}
    "npc_dota_hero_antimage"
	{
        "1"
        {
            // Abilities
            //-------------------------------------------------------------------------------------------------------------
            "HasScepterAndShard"    "1"
            "1"		"antimage_mana_break"
            "2"		"antimage_blink"
            "3"		"antimage_counterspell"
            "4"		"antimage_mana_overload"
            "5"		"antimage_counterspell_ally"
            "6"		"antimage_mana_void"
            "10"		"special_bonus_unique_antimage_4"
            "11"		"special_bonus_unique_antimage_manavoid_aoe"
            "12"		"special_bonus_unique_antimage_7"
            "13"		"special_bonus_unique_antimage_5"
            "14"		"special_bonus_unique_antimage_6"
            "15"		"special_bonus_unique_antimage"
            "16"		"special_bonus_unique_antimage_3"
            "17"		"special_bonus_unique_antimage_2"
        }
        "2"
        {
            "1"	"imba_antimage_mana_break"
            "2"	"imba_antimage_blink"
            "3"	"imba_antimage_spell_shield"
            "4"	"imba_antimage_mana_overload"
            "5"	"generic_hidden"
            "6"	"imba_antimage_mana_void"

            "10"	"special_bonus_imba_antimage_5"
            "11"	"special_bonus_armor_10"
            "12"	"special_bonus_imba_antimage_8"
            "13"	"special_bonus_imba_antimage_6"
            "14"	"special_bonus_imba_antimage_3"
            "15"	"special_bonus_imba_antimage_4"
            "16"	"special_bonus_imba_antimage_2"
            "17"	"special_bonus_unique_imba_antimage_1"
            "18"	"antimage_counterspell"
        }
		
	}

	//=================================================================================================================
	// HERO: Axe
	//=================================================================================================================
	"npc_dota_hero_axe"
	{
        "1"
        {
            "1"		"axe_berserkers_call"
            "2"		"axe_battle_hunger"
            "3"		"axe_counter_helix"
            "4"		"generic_hidden"
            "5"		"generic_hidden"
            "6"		"axe_culling_blade"
            "7"		"axe_coat_of_blood"
            "10"		"special_bonus_unique_axe_culling_blade_speed_duration"
            "11"		"special_bonus_unique_axe_8"
            "12"		"special_bonus_unique_axe_6"
            "13"		"special_bonus_unique_axe_4"
            "14"		"special_bonus_unique_axe_5"
            "15"		"special_bonus_unique_axe_7"
            "16"		"special_bonus_unique_axe_2"
            "17"		"special_bonus_unique_axe"
        }
        "2"
	    {
            "1"		"berserkers_call"	//"axe_berserkers_call"
            "2"		"battle_hunger"		//"axe_battle_hunger"
            "3"		"counter_helix"	//"axe_counter_helix"
            "4"		"axe_sprint"
            "5"		"generic_hidden"
            "6"		"culling_blade"				//"axe_culling_blade"
            "10"		"special_bonus_axe_1"
            "11"		"special_bonus_axe_2"
            "12"		"special_bonus_axe_5"
            "13"		"special_bonus_axe_4"
            "14"		"special_bonus_axe_3"
            "15"		"special_bonus_axe_6"
            "16"		"special_bonus_axe_7"
            "17"		"special_bonus_axe_8"
	    }
		
		
	}
   
	//=================================================================================================================
	// HERO: Bane
	//=================================================================================================================
	"npc_dota_hero_bane"
	{
		"1"{
            "1"		"bane_enfeeble"
            "2"		"bane_brain_sap"
            "3"		"bane_nightmare"
            "4"		"generic_hidden"
            "5"		"generic_hidden"
            "6"		"bane_fiends_grip"
            "7"		"bane_nightmare_end"
            "8"		"bane_ichor_of_nyctasha"
            "10"		"special_bonus_unique_bane_8"
            "11"		"special_bonus_unique_bane_11"
            "12"		"special_bonus_unique_bane_10"
            "13"		"special_bonus_unique_bane_9"
            "14"		"special_bonus_unique_bane_5"
            "15"		"special_bonus_movement_speed_30"
            "16"		"special_bonus_unique_bane_2"
            "17"		"special_bonus_unique_bane_3"
        }
        "2"
	    {
            "1"		"enfeeble"
            "2"		"brain_sap"
            "3"		"nightmare"
            "4"		"generic_hidden"
            "5"		"generic_hidden"
            "6"		"fiends_grip"
            "10"		"special_bonus_bane_1"
            "11"		"special_bonus_bane_2"
            "12"		"special_bonus_bane_3"
            "13"		"special_bonus_bane_4"
            "14"		"special_bonus_bane_5"
            "15"		"special_bonus_bane_6"
            "16"		"special_bonus_bane_7"
            "17"		"special_bonus_bane_8"
	    }
    }
   
	//=================================================================================================================
	// HERO: Bloodseeker
	//=================================================================================================================
	"npc_dota_hero_bloodseeker"
	{
        "1"
        {
            "1"		"bloodseeker_bloodrage"
            "2"		"bloodseeker_blood_bath"
            "3"		"bloodseeker_thirst"
            "4"		"bloodseeker_blood_mist"
            "5"		"bloodseeker_sanguivore"
            "6"		"bloodseeker_rupture"
            "10"		"special_bonus_unique_bloodseeker_5"
            "11"		"special_bonus_unique_bloodseeker_6"
            "12"		"special_bonus_unique_bloodseeker_7"
            "13"		"special_bonus_unique_bloodseeker_2"
            "14"		"special_bonus_unique_bloodseeker_3"
            "15"		"special_bonus_spell_lifesteal_15"
            "16"		"special_bonus_unique_bloodseeker_rupture_charges"
            "17"		"special_bonus_unique_bloodseeker_4"
        }
        "2"
        {
            "1"		"imba_bloodseeker_bloodrage"
            "2"		"imba_bloodseeker_blood_bath"
            "3"		"imba_bloodseeker_thirst"
            "4"		"generic_hidden"
            "5"		"generic_hidden"
            "6"		"imba_bloodseeker_rupture"

            "10"		"special_bonus_imba_bloodseeker_1"
            "11"		"special_bonus_imba_bloodseeker_2"
            "12"		"special_bonus_imba_bloodseeker_3"
            "13"		"special_bonus_imba_bloodseeker_4"
            "14"		"special_bonus_imba_bloodseeker_5"
            "15"		"special_bonus_imba_bloodseeker_6"
            "16"		"special_bonus_imba_bloodseeker_7"
            "17"		"special_bonus_imba_bloodseeker_8"
        }
		
		
	}

	//=================================================================================================================
	// HERO: Crystal Maiden
	//=================================================================================================================
	"npc_dota_hero_crystal_maiden"
	{
        "1"
        {
            "1"		"crystal_maiden_crystal_nova"
            "2"		"crystal_maiden_frostbite"
            "3"		"crystal_maiden_brilliance_aura"
            "4"		"crystal_maiden_crystal_clone"
            "5"		"crystal_maiden_blueheart_floe"
            "6"		"crystal_maiden_freezing_field"
            "7"		"crystal_maiden_freezing_field_stop"
            "10"		"special_bonus_hp_250"
            "11"		"special_bonus_unique_crystal_maiden_6"
            "12"		"special_bonus_unique_crystal_maiden_frostbite_castrange"
            "13"		"special_bonus_unique_crystal_maiden_5"
            "14"		"special_bonus_attack_speed_225"
            "15"		"special_bonus_unique_crystal_maiden_3"
            "16"		"special_bonus_unique_crystal_maiden_1"
            "17"		"special_bonus_unique_crystal_maiden_2"
        }
        "2"
	    {
            "1"		"crystal_nova"//"crystal_maiden_crystal_nova"
            "2"		"frostbite"//"crystal_maiden_frostbite"
            "3"		"brilliance_aura"//"crystal_maiden_brilliance_aura"
            "4"		"generic_hidden"
            "5"		"generic_hidden"
            "6"		"freezing_field"//"crystal_maiden_freezing_field"
            "10"		"special_bonus_crystal_maiden_1"
            "11"		"special_bonus_crystal_maiden_2"
            "12"		"special_bonus_crystal_maiden_3"
            "13"		"special_bonus_crystal_maiden_4"
            "14"		"special_bonus_crystal_maiden_5"
            "15"		"special_bonus_crystal_maiden_6"
            "16"		"special_bonus_crystal_maiden_7"
            "17"		"special_bonus_crystal_maiden_8"
	    }
	}
    
   
	"npc_dota_hero_drow_ranger"
	{
		"1"
        {
            "1"		"drow_ranger_frost_arrows"
            "2"		"drow_ranger_wave_of_silence"
            "3"		"drow_ranger_multishot"
            "4"		"drow_ranger_glacier"
            "5"		"drow_ranger_trueshot"
            "6"		"drow_ranger_marksmanship"
            "10"		"special_bonus_unique_drow_ranger_7"
            "11"		"special_bonus_unique_drow_ranger_2"
            "12"		"special_bonus_lifesteal_20"
            "13"		"special_bonus_unique_drow_ranger_6"
            "14"		"special_bonus_unique_drow_ranger_1"
            "15"		"special_bonus_unique_drow_ranger_gust_selfmovespeed"
            "16"		"special_bonus_unique_drow_ranger_3"
            "17"		"special_bonus_unique_drow_ranger_8"
        }
		"2"
        {
            "1"		"frost_arrows"
            "2"		"wave_of_silence"
            "3"		"multishot"
            "4"		"generic_hidden"
            "5"		"drow_ranger_marksmanship"
            "6"		"marksmanship"
            "10"		"special_bonus_drow_ranger_1"
            "11"		"special_bonus_drow_ranger_2"
            "12"		"special_bonus_drow_ranger_3"
            "13"		"special_bonus_drow_ranger_4"
            "14"		"special_bonus_drow_ranger_5"
            "15"		"special_bonus_drow_ranger_6"
            "16"		"special_bonus_drow_ranger_7"
            "17"		"special_bonus_drow_ranger_8"
        }
	}
	"npc_dota_hero_earthshaker"
	{
        
        "1"
        {
            "1"		"earthshaker_fissure"
            "2"		"earthshaker_enchant_totem"
            "3"		"earthshaker_aftershock"
            "4"		"generic_hidden"
            "5"		"generic_hidden"
            "6"		"earthshaker_echo_slam"
            "10"		"special_bonus_attack_base_damage_30"
            "11"		"special_bonus_unique_earthshaker_4"
            "12"		"special_bonus_unique_earthshaker_3"
            "13"		"special_bonus_unique_earthshaker_6"
            "14"		"special_bonus_unique_earthshaker_2"
            "15"		"special_bonus_unique_earthshaker_totem_damage"
            "16"		"special_bonus_unique_earthshaker_echo_cd"
            "17"		"special_bonus_unique_earthshaker"
        }
        "2"
        {
            "1"	"imba_earthshaker_fissure"
            "2"	"imba_earthshaker_enchant_totem"
            "3"	"imba_earthshaker_aftershock"
            "4"	"generic_hidden"
            "5"	"imba_earthshaker_stars_aura"
            "6"	"imba_earthshaker_echo_slam"
            
            "10"	"special_bonus_imba_earthshaker_7"
            "11"	"special_bonus_cast_range_100"
            "12"	"special_bonus_imba_earthshaker_6"
            "13"	"special_bonus_imba_earthshaker_4" 
            "14"	"special_bonus_imba_earthshaker_3"
            "15"	"special_bonus_imba_earthshaker_5"
            "16"	"special_bonus_imba_earthshaker_2"
            "17"	"special_bonus_imba_earthshaker_1"
        }	
	}
	"npc_dota_hero_juggernaut"
	{
        "1"
        {
            "1"		"juggernaut_blade_fury"
            "2"		"juggernaut_healing_ward"
            "3"		"juggernaut_blade_dance"
            "4"		"juggernaut_swift_slash"
            "5"		"juggernaut_duelist"
            "6"		"juggernaut_omni_slash"
            "10"		"special_bonus_unique_juggernaut_4"
            "11"		"special_bonus_unique_juggernaut_3"
            "12"		"special_bonus_unique_juggernaut_5"
            "13"		"special_bonus_unique_juggernaut_blade_fury_movespeed"
            "14"		"special_bonus_unique_juggernaut_blade_dance_lifesteal"
            "15"		"special_bonus_unique_juggernaut_blade_fury_cooldown"
            "16"		"special_bonus_unique_juggernaut_omnislash_duration"
        }
        "2"
        {
            "1"		"blade_fury"//"juggernaut_blade_fury"
            "2"		"healing_ward"//"juggernaut_healing_ward"
            "3"		"blade_dance" //"juggernaut_blade_dance"
            "4"		"swift_slash2"//"juggernaut_swift_slash"
            "5"		"generic_hidden"
            "6"		"omni_slash"//"juggernaut_omni_slash"
            "10"		"special_bonus_juggernaut_1"
            "11"		"special_bonus_juggernaut_2"
            "12"		"special_bonus_juggernaut_3"
            "13"		"special_bonus_juggernaut_4"
            "14"		"special_bonus_juggernaut_5"
            "15"		"special_bonus_juggernaut_6"
            "16"		"special_bonus_juggernaut_7"
            "17"		"special_bonus_juggernaut_8"
        }
	}
	"npc_dota_hero_mirana"
	{
		"1"
        {
        "1"		"mirana_starfall"
		"2"		"mirana_arrow"
		"3"		"mirana_leap"
		"4"		"mirana_selemenes_faithful"
		"5"		"generic_hidden"
		"6"		"generic_hidden"
		"10"		"special_bonus_unique_mirana_3"
		"11"		"special_bonus_unique_mirana_6"
		"12"		"special_bonus_unique_mirana_5"
		"13"		"special_bonus_unique_mirana_1"
		"14"		"special_bonus_unique_mirana_4"
		"15"		"special_bonus_20_crit_2"
		"16"		"special_bonus_unique_mirana_2"
		"17"		"special_bonus_unique_mirana_7"
        }
        "2"
        {
        "1"	"imba_mirana_starfall"
		"2"	"imba_mirana_arrow"
		"3"	"imba_mirana_leap"
		"4"	"imba_mirana_cosmic_dust"
		"5"	"generic_hidden"
		"6"	"imba_mirana_moonlight_shadow"
		"10"	"special_bonus_agility_13"
		"11"	"special_bonus_hp_150"
		"12"	"special_bonus_spell_amplify_6"
		"13"	"special_bonus_attack_speed_20"
		"14"	"special_bonus_attack_damage_40"
		"15"	"special_bonus_imba_mirana_2"
		"16"	"special_bonus_attack_range_100"
		"17"	"special_bonus_imba_mirana_1"
		"7"	""
		"8"	""
		"9"	""
        }
			
	}
	"npc_dota_hero_nevermore"
	{
		"1"{
        "1"		"nevermore_shadowraze1"
		"2"		"nevermore_shadowraze2"
		"3"		"nevermore_shadowraze3"
		"4"		"nevermore_frenzy"
		"5"		"nevermore_dark_lord"
		"6"		"nevermore_requiem"
		"7"		"nevermore_necromastery"
		"10"		"special_bonus_unique_nevermore_7"
		"11"		"special_bonus_unique_nevermore_4"
		"12"		"special_bonus_unique_nevermore_3"
		"13"		"special_bonus_unique_nevermore_2"
		"14"		"special_bonus_unique_nevermore_1"
		"15"		"special_bonus_unique_nevermore_6"
		"16"		"special_bonus_unique_nevermore_frenzy_castspeed"
		"17"		"special_bonus_unique_nevermore_raze_procsattacks"
        }
		
         "2"
        {
            "1"	"imba_nevermore_shadowraze1"
		"2"	"imba_nevermore_shadowraze2"
		"3"	"imba_nevermore_shadowraze3"
		"4"	"imba_nevermore_necromastery"
		"5"	"generic_hidden"
		"6"	"imba_nevermore_requiem"
		"10"	"special_bonus_custom_value_agi20"  //60
		"11""special_bonus_custom_value_mgr10"  //40
		"12"	"special_bonus_custom_value_ap15"  //500
		"13""special_bonus_movement_speed_40"	  //25
		"14""special_bonus_attack_speed_60" //200
		"15"	"special_bonus_imba_nevermore_2"
		"16"	"special_bonus_imba_nevermore_4"
		"17"	"special_bonus_custom_value_cd30"
		"7"	"imba_nevermore_dark_lord"
		"8"	""
		"9"	""
        }
	}
	"npc_dota_hero_phantom_lancer"
	{
		"1"{
	    "1"		"phantom_lancer_spirit_lance"
		"2"		"phantom_lancer_doppelwalk"
		"3"		"phantom_lancer_phantom_edge"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"phantom_lancer_juxtapose"
		"10"		"special_bonus_unique_phantom_lancer_lance_damage"
		"11"		"special_bonus_unique_phantom_lancer_phantom_rush_agility"
		"12"		"special_bonus_unique_phantom_lancer_2"
		"13"		"special_bonus_unique_phantom_lancer_5"
		"14"		"special_bonus_unique_phantom_lancer"
		"15"		"special_bonus_unique_phantom_lancer_6"
		"16"		"special_bonus_unique_phantom_lancer_4"
		"17"		"special_bonus_20_crit_2"
        }
	
	 "2"
        {
            "1"		"imba_phantom_lancer_spirit_lance"
		"2"		"imba_phantom_lancer_doppelwalk"
		"3"		"imba_phantom_lancer_phantom_edge"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"imba_phantom_lancer_juxtapose"
		"10"		"special_bonus_imba_phantom_lancer_5"
		"11"		"special_bonus_imba_phantom_lancer_4"
		"12"		"special_bonus_imba_phantom_lancer_2"
		"13"		"special_bonus_imba_phantom_lancer_7"
		"14"		"special_bonus_imba_phantom_lancer_6"
		"15"		"special_bonus_imba_phantom_lancer_1"
		"16"		"special_bonus_imba_phantom_lancer_3"
		"17"		"special_bonus_24_crit_2"
        }
	}
	"npc_dota_hero_puck"
	{
        "1"	
        {
        "1"		"puck_illusory_orb"
		"2"		"puck_waning_rift"
		"3"		"puck_phase_shift"
		"4"		"puck_ethereal_jaunt"
		"5"		"puck_puckish"
		"6"		"puck_dream_coil"
		"10"		"special_bonus_unique_puck_orb_damage"
		"11"		"special_bonus_unique_puck_7"
		"12"		"special_bonus_unique_puck"
		"13"		"special_bonus_unique_puck_6"
		"14"		"special_bonus_unique_puck_2"
		"15"		"special_bonus_unique_puck_coil_damage"
		"16"		"special_bonus_unique_puck_5"
		"17"		"special_bonus_unique_puck_rift_radius"
        }
		
		"2"
		{
			"1"	"imba_puck_illusory_orb"
		"2"	"imba_puck_waning_rift"
		"3"	"imba_puck_phase_shift"
		"4"	"imba_puck_ethereal_jaunt"
		"5"	"generic_hidden"
		"6"	"imba_puck_dream_coil"
		"10"	"special_bonus_imba_puck_3"
		"11"	"special_bonus_imba_puck_6"
		"12"	"special_bonus_imba_puck_5"
		"13"	"special_bonus_imba_puck_8"
		"14"	"special_bonus_imba_puck_7"
		"15"	"special_bonus_imba_puck_2"
		"16"	"special_bonus_imba_puck_4"
		"17"	"special_bonus_imba_puck_1"
		"7"	""
		"8"	""
		"9"	""
		}

	
	}
	"npc_dota_hero_pudge"
	{
		"1"	{
        "1"		"pudge_meat_hook"
		"2"		"pudge_rot"
		"3"		"pudge_flesh_heap"
		"4"		"pudge_eject"
		"5"		"pudge_innate_graft_flesh"
		"6"		"pudge_dismember"
		"10"		"special_bonus_armor_5"
		"11"		"special_bonus_unique_pudge_4"
		"12"		"special_bonus_spell_lifesteal_8"
		"13"		"special_bonus_unique_pudge_7"
		"14"		"special_bonus_unique_pudge_6"
		"15"		"special_bonus_unique_pudge_5"
		"16"		"special_bonus_unique_pudge_3"
		"17"		"special_bonus_unique_pudge_1"
        }
		
		"2"
		{
			"1"		"meat_hook"
            "2"		"prot"
            "3"		"flesh_heap"
            "4"		"generic_hidden"
            "5"		"generic_hidden"
            "6"		"dismember"
            "10"		"special_bonus_pudge_1"
            "11"		"special_bonus_pudge_2"
            "12"		"special_bonus_pudge_3"
            "13"		"special_bonus_pudge_4"
            "14"		"special_bonus_pudge_5"
            "15"		"special_bonus_pudge_6"
            "16"		"special_bonus_pudge_7"
            "17"		"special_bonus_pudge_8"
		}
		
	}
	"npc_dota_hero_razor"
	{
		"1"
        {
            "1"		"razor_plasma_field"
            "2"		"razor_static_link"
            "3"		"razor_storm_surge"
            "4"		"razor_unstable_current"
            "5"		"generic_hidden"
            "6"		"razor_eye_of_the_storm"
            "10"		"special_bonus_unique_razor_4"
            "11"		"special_bonus_spell_lifesteal_10"
            "12"		"special_bonus_unique_razor"
            "13"		"special_bonus_unique_razor_3"
            "14"		"special_bonus_unique_razor_storm_surge_damage_and_slow"
            "15"		"special_bonus_unique_razor_2"
            "16"		"special_bonus_unique_razor_plasmafield_second_ring"
            "17"		"special_bonus_unique_razor_static_link_aspd"
        }
		
		"2"
		{
			"1"	"imba_razor_plasma_field"
            "2"	"imba_razor_static_link"
            "3"	"imba_razor_unstable_current"
            "4"	"imba_razor_whip"
            "5"	"generic_hidden"
            "6"	"imba_razor_eye_of_the_storm"
            "10"	"special_bonus_movement_speed_15"
            "11"	"special_bonus_imba_razor_1"
            "12"	"special_bonus_cast_range_125"
            "13"	"special_bonus_imba_razor_2"
            "14"	"special_bonus_imba_razor_3"
            "15"	"special_bonus_imba_razor_6"
            "16"	"special_bonus_imba_razor_4"
            "17"	"special_bonus_imba_razor_5"
            "7"	""
            "8"	""
            "9"	""
		}
	}
	"npc_dota_hero_sand_king"
	{
	
        "1"
        {
            "1"		"sandking_burrowstrike"
            "2"		"sandking_sand_storm"
            "3"		"sandking_scorpion_strike"
            "4"		"sandking_caustic_finale"
            "5"		"generic_hidden"
            "6"		"sandking_epicenter"
            "10"		"special_bonus_unique_sand_king_2"
            "11"		"special_bonus_unique_sand_king_burrowstrike_stun"
            "12"		"special_bonus_unique_sand_king_3"
            "13"		"special_bonus_unique_sand_king_scorpion_strike_damage"
            "14"		"special_bonus_unique_sand_king_7"
            "15"		"special_bonus_unique_sand_king_5"
            "16"		"special_bonus_unique_sand_king"
            "17"		"special_bonus_unique_sand_king_4"
        }
		
		
		"2"
		{
			"1"		"burrowstrike"
            "2"		"sand_storm"
            "3"		"caustic_finale"
            "4"		"generic_hidden"
            "5"		"generic_hidden"
            "6"		"epicenter"
            "10"		"special_bonus_sand_king_7"
            "11"		"special_bonus_sand_king_2"
            "12"		"special_bonus_sand_king_3"
            "13"		"special_bonus_sand_king_4"
            "14"		"special_bonus_sand_king_6"
            "15"		"special_bonus_sand_king_1"
            "16"		"special_bonus_sand_king_5"
            "17"		"special_bonus_sand_king_8"
			
		}
		
		
	}
	"npc_dota_hero_storm_spirit"
	{   
        "1"{
            "1"		"storm_spirit_static_remnant"
            "2"		"storm_spirit_electric_vortex"
            "3"		"storm_spirit_overload"
            "4"		"generic_hidden"
            "5"		"generic_hidden"
            "6"		"storm_spirit_ball_lightning"
            "7"		"storm_spirit_galvanized"
            "10"		"special_bonus_unique_storm_spirit_overload_aspd"
            "11"		"special_bonus_mp_regen_150"
            "12"		"special_bonus_hp_250"
            "13"		"special_bonus_unique_storm_spirit_5"
            "14"		"special_bonus_unique_storm_spirit"
            "15"		"special_bonus_unique_storm_spirit_8"
            "16"		"special_bonus_unique_storm_spirit_7"
            "17"		"special_bonus_unique_storm_spirit_4"
        }
		
		"2"
		{
			"1"	"imba_storm_spirit_static_remnant"
            "2"	"imba_storm_spirit_electric_vortex"
            "3"	"imba_storm_spirit_overload"
            "4"	"electric_rave"
            "5"	"generic_hidden"
            "6"	"imba_storm_spirit_ball_lightning"
            "10"	"special_bonus_imba_storm_spirit_7"
            "11"	"special_bonus_imba_storm_spirit_8"
            "12"	"special_bonus_imba_storm_spirit_1"
            "13"	"special_bonus_imba_storm_spirit_2"
            "14"	"special_bonus_imba_storm_spirit_5"
            "15"	"special_bonus_imba_storm_spirit_6"
            "16"	"special_bonus_imba_storm_spirit_4"
            "17"	"special_bonus_imba_storm_spirit_3"
		}

	
	}
	"npc_dota_hero_sven"
	{
        "1"{
            "1"		"sven_storm_bolt"
            "2"		"sven_great_cleave"
            "3"		"sven_warcry"
            "4"		"generic_hidden"
            "5"		"generic_hidden"
            "6"		"sven_gods_strength"
            "7"		"sven_vanquisher"
            "10"		"special_bonus_unique_sven_5"
            "11"		"special_bonus_attack_speed_15"
            "12"		"special_bonus_unique_sven_3"
            "13"		"special_bonus_unique_sven_8"
            "14"		"special_bonus_unique_sven_gods_strength_slow_resist"
            "15"		"special_bonus_unique_sven_7"
            "16"		"special_bonus_unique_sven_2"
            "17"		"special_bonus_unique_sven_4"
            }
		
		"2"
		{
			"AttackRate"		"1.700000"
            "1"		"storm_bolt"	//"sven_storm_bolt"
            "2"		"great_cleave"	//"sven_great_cleave"
            "3"		"warcry"//"sven_warcry"
            "4"		"generic_hidden"
            "5"		"generic_hidden"
            "6"		"gods_strength"//"sven_gods_strength"
            "10"		"special_bonus_sven_1"
            "11"		"special_bonus_sven_2"
            "12"		"special_bonus_sven_3"
            "13"		"special_bonus_sven_4"
            "14"		"special_bonus_sven_5"
            "15"		"special_bonus_sven_6"
            "16"		"special_bonus_sven_7"
            "17"		"special_bonus_sven_8"
		}
		
	}
	"npc_dota_hero_tiny"
	{
        "1"{
            "1"		"tiny_avalanche"
		"2"		"tiny_toss"
		"3"		"tiny_tree_grab"
		"4"		"tiny_tree_channel"
		"5"		"tiny_craggy_exterior"
		"6"		"tiny_grow"
		"7"		"tiny_toss_tree"
		"10"		"special_bonus_unique_tiny_4"
		"11"		"special_bonus_strength_10"
		"12"		"special_bonus_unique_tiny_6"
		"13"		"special_bonus_unique_tiny"
		"14"		"special_bonus_unique_tiny_7"
		"15"		"special_bonus_unique_tiny_5"
		"16"		"special_bonus_unique_tiny_3"
		"17"		"special_bonus_unique_tiny_2"
        }
		

		"2"
		{
			"1"		"imba_tiny_avalanche"
		"2"		"imba_tiny_toss"
		"3"		"imba_tiny_tree_grab"
		"4"		"imba_tiny_craggy_exterior"
		"5"		"imba_tiny_tree_channel"
		"6"		"imba_tiny_grow"
		"7"		"imba_tiny_toss_tree"

		"10"		"special_bonus_attack_speed_40"
		"11"		"special_bonus_movement_speed_20"
		"12"		"special_bonus_imba_tiny_3"
		"13"		"special_bonus_imba_tiny_4"
		"14"		"special_bonus_imba_tiny_5"
		"15"		"special_bonus_imba_tiny_6"
		"16"		"special_bonus_imba_tiny_7"
		"17"		"special_bonus_imba_tiny_8"
		}

		
	}
	"npc_dota_hero_vengefulspirit"
	{
	
        "1"
        {
        "1"		"vengefulspirit_magic_missile"
		"2"		"vengefulspirit_wave_of_terror"
		"3"		"vengefulspirit_command_aura"
		"4"		"vengefulspirit_retribution"
		"5"		"generic_hidden"
		"6"		"vengefulspirit_nether_swap"
		"10"		"special_bonus_unique_vengeful_spirit_swap_damage"
		"11"		"special_bonus_unique_vengeful_spirit_missile_castrange"
		"12"		"special_bonus_unique_vengeful_spirit_4"
		"13"		"special_bonus_unique_vengeful_spirit_1"
		"14"		"special_bonus_unique_vengeful_spirit_5"
		"15"		"special_bonus_unique_vengeful_spirit_wave_of_terror_steal"
		"16"		"special_bonus_unique_vengeful_spirit_2"
		"17"		"special_bonus_unique_vengeful_spirit_9"
        }
		
		"2"
		{
			"1"		"magic_missile"
		"2"		"wave_of_terror"
		"3"		"vengefulspirit_command_aura"
		"4"		"command_aura"
		"5"		"vs_return"
		"6"		"nether_swap"
		"10"		"special_bonus_vengefulspirit_5"
		"11"		"special_bonus_vengefulspirit_6"
		"12"		"special_bonus_vengefulspirit_4"
		"13"		"special_bonus_vengefulspirit_7"
		"14"		"special_bonus_vengefulspirit_1"
		"15"		"special_bonus_vengefulspirit_2"
		"16"		"special_bonus_vengefulspirit_3"
		"17"		"special_bonus_unique_vengeful_spirit_2"
		}
		
	}
	"npc_dota_hero_windrunner"
	{
        "1"{
            "1"		"windrunner_shackleshot"
            "2"		"windrunner_powershot"
            "3"		"windrunner_windrun"
            "4"		"windrunner_gale_force"
            "5"		"windrunner_focusfire_cancel"
            "6"		"windrunner_focusfire"
            "7"		"windrunner_easy_breezy"
            "10"		"special_bonus_unique_windranger_powershot_slow"
            "11"		"special_bonus_unique_windranger_9"
            "12"		"special_bonus_unique_windranger_4"
            "13"		"special_bonus_unique_windranger_3"
            "14"		"special_bonus_unique_windranger_6"
            "15"		"special_bonus_unique_windranger_8"
            "16"		"special_bonus_unique_windranger_windrun_undispellable"
            "17"		"special_bonus_unique_windranger_2"
        }
		"2"
		{
			
		"1"		"shackleshot"	//"windrunner_shackleshot"
		"2"		"powershot"	//"windrunner_powershot"
		"3"		"windrun"//"windrunner_windrun"
		"4"		"windrunner_gale_force"
		"5"		"generic_hidden"
		"6"		"focusfire"//"windrunner_focusfire"

		"10"		"special_bonus_windrunner_1"
		"11"		"special_bonus_windrunner_2"
		"12"		"special_bonus_windrunner_3"
		"13"		"special_bonus_windrunner_4"
		"14"		"special_bonus_unique_imba_windrunner_5"
		"15"		"special_bonus_unique_imba_windrunner_6"
		"16"		"special_bonus_windrunner_7"
		"17"		"special_bonus_windrunner_8"
		}
		
	}
	"npc_dota_hero_zuus"
	{
        "1"
        {
        "1"		"zuus_arc_lightning"
		"2"		"zuus_lightning_bolt"
		"3"		"zuus_heavenly_jump"
		"4"		"zuus_cloud"
		"5"		"zuus_lightning_hands"
		"6"		"zuus_thundergods_wrath"
		"7"		"zuus_static_field"	
		"10"		"special_bonus_unique_zeus_jump_cooldown"
		"11"		"special_bonus_hp_250"
		"12"		"special_bonus_unique_zeus_jump_postjump_movespeed"
		"13"		"special_bonus_unique_zeus"
		"14"		"special_bonus_unique_zeus_2"
		"15"		"special_bonus_unique_zeus_3"
		"16"		"special_bonus_unique_zeus_5"
		"17"		"special_bonus_unique_zeus_4"
        }
		
        "2"
		{
			"1"		"dlzuus_al"
			"2"		"dlzuus_ts"
			"3"		"dlzuus_sf"
			"4"		"zuus_cloud"
			"5"		"generic_hidden"
			"6"		"zuus_thundergods_wrath"
			"10"		"special_bonus_attack_speed_100"	//10r攻击速度加50
			"11"		"special_bonus_mp_regen_10"	//10l回蓝加10
			"12"		"special_bonus_attack_range_150"	//15r攻击距离加100
			"13"		"special_bonus_movement_speed_40"	//15l移动速度加40
			"14"		"special_bonus_dlzuus_20r"	//20r	智能量系数加1
			"15"		"special_bonus_dlzuus_20l"	//20l	雷枪可穿透非英雄单位
			"16"		"special_bonus_dlzuus_25r"	//25r	注雷弹跳范围加300
			"17"		"special_bonus_dlzuus_25l"	//25l	静电场伤害加2%
			"7"		"zuus_lightning_bolt"	//override里需要hide一下
			"8"	""
			"9"	""
		}
		
		
	}
	"npc_dota_hero_kunkka"
	{
	    "1"
        {
        "1"		"kunkka_torrent"
		"2"		"kunkka_tidebringer"
		"3"		"kunkka_x_marks_the_spot"
		"4"		"kunkka_torrent_storm"
		"5"		"kunkka_tidal_wave"
		"6"		"kunkka_ghostship"
		"7"		"kunkka_return"
		"10"		"special_bonus_unique_kunkka_tidebringer_slow"
		"11"		"special_bonus_unique_kunkka_6"
		"12"		"special_bonus_unique_kunkka_7"
		"13"		"special_bonus_unique_kunkka_2"
		"14"		"special_bonus_unique_kunkka_torrent_cooldown"
		"15"		"special_bonus_unique_kunkka_rum"
		"16"		"special_bonus_unique_kunkka_3"
		"17"		"special_bonus_unique_kunkka_4"
		
        }
        "2"
		{
				"1"		"torrent"//"kunkka_torrent"
		"2"		"tidebringer"//"kunkka_tidebringer"
		"3"		"x_marks_the_spot"//"kunkka_x_marks_the_spot"
		"4"		"ghostship_storm"//"kunkka_torrent_storm"
		"5"		"kunkka_tidal_wave"
		"6"		"ghostship"//"kunkka_ghostship"
		"7"		"x_return"//"kunkka_return"
		"10"		"special_bonus_kunkka_1"
		"11"		"special_bonus_kunkka_2"
		"12"		"special_bonus_kunkka_7"
		"13"		"special_bonus_kunkka_4"
		"14"		"special_bonus_kunkka_5"
		"15"		"special_bonus_kunkka_6"
		"16"		"special_bonus_kunkka_3"
		"17"		"special_bonus_kunkka_8"

		}
		
		
		
		
    }

   "npc_dota_hero_lina"
    {
        "1"	
        {
         "1"		"lina_dragon_slave"
		"2"		"lina_light_strike_array"
		"3"		"lina_fiery_soul"
		"4"		"lina_flame_cloak"
		"5"		"generic_hidden"
		"6"		"lina_laguna_blade"
		"10"		"special_bonus_attack_damage_25"
		"11"		"special_bonus_unique_lina_1"
		"12"		"special_bonus_unique_lina_4"
		"13"		"special_bonus_unique_lina_3"
		"14"		"special_bonus_unique_lina_6"
		"15"		"special_bonus_unique_lina_2"
		"16"		"special_bonus_unique_lina_7"
		"17"		"special_bonus_unique_lina_dragon_slave_crits"
        }
        "2"
        {
            "HasScepterAndShard"    "1"
            "Author"
            {
                "name"      "新英霸火女"
                "tip"       "<br>极致化的K头"
                "portrait"  ""
            }
            "1"		    "dragon_slave"
            "2"		    "light_strike_array"
            "3"		     "fiery_soul"
            "4"		    "generic_hidden"
            "5"		    "generic_hidden"
            "6"		    "laguna_blade"
            "10"		"special_bonus_lina_1"
            "11"		"special_bonus_lina_2"
            "12"		"special_bonus_lina_3"
            "13"		"special_bonus_lina_4"
            "14"		"special_bonus_lina_5"
            "15"		"special_bonus_lina_6"
            "16"		"special_bonus_lina_7"
            "17"		"special_bonus_lina_8"
        }
        "3"
        {
            "HasScepterAndShard"    "0"
            "Author"
            {
                "name"      "旧英霸火女"
                "tip"       "<br>短CD ,无脑甩技能"
                "portrait"  ""
            }
            "1"		    "imba_lina_dragon_slave"
            "2"		   "imba_lina_light_strike_array"
            "3"		    "imba_lina_fiery_soul"
            "4"		   "generic_hidden"
            "5"		    "generic_hidden"
            "6"		    "imba_lina_laguna_blade"
            "10"		"special_bonus_custom_value_msp30"
            "11"		"special_bonus_custom_value_all15"
            "12"		"special_bonus_custom_value_castrange100"
            "13"		"special_bonus_attack_range_100"
            "14"		"special_bonus_custom_value_ap15"
            "15"		"special_bonus_custom_value_cd10"
            "16"		"special_bonus_attack_speed_160"
            "17"		"special_bonus_attack_damage_150"
        }
    }
	"npc_dota_hero_lich"
	{
		"1"
        {
        "1"       "lich_frost_nova"
		"2"		"lich_frost_shield"
		"3"		"lich_sinister_gaze"
		"4"		"lich_ice_spire"
		"5"		"lich_death_charge"
		"6"		"lich_chain_frost"
		"10"		"special_bonus_unique_lich_8"
		"11"		"special_bonus_unique_lich_6"
		"12"		"special_bonus_unique_lich_2"
		"13"		"special_bonus_unique_lich_3"
		"14"		"special_bonus_unique_lich_7"
		"15"		"special_bonus_unique_lich_4"
		"16"		"special_bonus_unique_lich_1"
		"17"		"special_bonus_unique_lich_5"
        }		
		
		"2"
		{
			"1"	"imba_lich_frost_nova"
		"2"	"imba_lich_frost_armor"
		"3"	"imba_lich_sinister_gaze"
		"4"	"imba_lich_ice_spire"
		"5"	"generic_hidden"
		"6"	"imba_lich_chain_frost"
		"10"	"special_bonus_imba_lich_7"
		"11"	"special_bonus_imba_lich_8"
		"12"	"special_bonus_imba_lich_5"
		"13"	"special_bonus_imba_lich_4"
		"14"	"special_bonus_imba_lich_3"
		"15"	"special_bonus_imba_lich_1"
		"16"	"special_bonus_imba_lich_6"
		"17"	"special_bonus_imba_lich_2"
		}
		
	}
	"npc_dota_hero_lion"
	{
		
		"1"	
        {
        "1"		"lion_impale"
		"2"		"lion_voodoo"
		"3"		"lion_mana_drain"
		"4"		"lion_to_hell_and_back"
		"5"		"generic_hidden"
		"6"		"lion_finger_of_death"
		"10"		"special_bonus_unique_lion_6"
		"11"		"special_bonus_unique_lion_3"
		"12"		"special_bonus_unique_lion_5"
		"13"		"special_bonus_unique_lion_11"
		"14"		"special_bonus_unique_lion_8"
		"15"		"special_bonus_unique_lion_10"
		"16"		"special_bonus_unique_lion_2"
		"17"		"special_bonus_unique_lion_4"
        }
		"2"
		{
			"1"	"imba_lion_earth_spike"//"imba_lion_earth_spike"
		"2"	"imba_lion_hex"
		"3"	"imba_lion_mana_drain"
		"4"	"generic_hidden"
		"5"	"generic_hidden"
		"6"	"imba_lion_finger_of_death"
		"10"		"special_bonus_imba_lion_5"
		"11"		"special_bonus_imba_lion_7"
		"12"		"special_bonus_imba_lion_2"//"special_bonus_imba_lion_2"  
		"13"		"special_bonus_cast_range_125"
		"14"		"special_bonus_imba_lion_4"
		"15"		"special_bonus_imba_lion_3"//"special_bonus_imba_lion_3"
		"16"		"special_bonus_imba_lion_1"
		"17"		"special_bonus_imba_lion_6" 
		"7"	""
		"8"	""
		"9"	""
		}
	
	}
	"npc_dota_hero_shadow_shaman"
	{
		"1"	{

            "1"		"shadow_shaman_ether_shock"
		"2"		"shadow_shaman_voodoo"
		"3"		"shadow_shaman_shackles"
		"4"		"shadow_shaman_fowl_play"
		"5"		"generic_hidden"
		"6"		"shadow_shaman_mass_serpent_ward"
		"10"		"special_bonus_unique_shadow_shaman_6"
		"11"		"special_bonus_unique_shadow_shaman_hex_damage_amp"
		"12"		"special_bonus_unique_shadow_shaman_8"
		"13"		"special_bonus_unique_shadow_shaman_2"
		"14"		"special_bonus_unique_shadow_shaman_7"
		"15"		"special_bonus_unique_shadow_shaman_1"
		"16"		"special_bonus_unique_shadow_shaman_3"
		"17"		"special_bonus_unique_shadow_shaman_4"
		
		}
            "2"
		{
			"1"		"shock"//"shadow_shaman_ether_shock"
		"2"		"voodoo"//"shadow_shaman_voodoo"
		"3"		"shackles"//"shadow_shaman_shackles"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"serpent_ward"//"shadow_shaman_mass_serpent_ward"
		"10"		"special_bonus_shadow_shaman_1"
		"11"		"special_bonus_shadow_shaman_2"
		"12"		"special_bonus_shadow_shaman_3"
		"13"		"special_bonus_shadow_shaman_4"
		"14"		"special_bonus_shadow_shaman_5"
		"15"		"special_bonus_shadow_shaman_6"
		"16"		"special_bonus_custom_value_ap25"
		"17"		"special_bonus_custom_value_castrange150"

		}
		
		
	}
	"npc_dota_hero_slardar"
	{
	
		"1"	
        {
            "1"		"slardar_sprint"
		"2"		"slardar_slithereen_crush"
		"3"		"slardar_bash"
		"4"		"slardar_seaborn_sentinel"
		"5"		"generic_hidden"
		"6"		"slardar_amplify_damage"
		"10"		"special_bonus_unique_slardar_7"
		"11"		"special_bonus_unique_slardar_slithereen_crush_stun"
		"12"		"special_bonus_hp_325"
		"13"		"special_bonus_unique_slardar_2"
		"14"		"special_bonus_unique_slardar"
		"15"		"special_bonus_unique_slardar_5"
		"16"		"special_bonus_unique_slardar_4"
		"17"		"special_bonus_unique_slardar_3"
        }
        "2"
		{
				"1"	"imba_slardar_sprint"
		"2"	"imba_slardar_slithereen_crush"
		"3"	"imba_slardar_bash"
		"4"	"generic_hidden"
		"5"	"generic_hidden"
		"6"	"imba_slardar_trap"
		"10"	"special_bonus_lifesteal_20"
		"11"	"special_bonus_exp_boost_15"
		"12"	"special_bonus_imba_slardar_1"
		"13"	"special_bonus_imba_slardar_2"
		"14"	"special_bonus_attack_speed_60"
		"15"	"special_bonus_night_vision_1000"
		"16"	"special_bonus_imba_slardar_3"
		"17"	"special_bonus_strength_40"
		}		
		
	}
	"npc_dota_hero_tidehunter"
	{
		
		"1"	
        {
            "1"		"tidehunter_gush"
		"2"		"tidehunter_kraken_shell"
		"3"		"tidehunter_anchor_smash"
		"4"		"tidehunter_dead_in_the_water"
		"5"		"generic_hidden"
		"6"		"tidehunter_ravage"
		"7"		"tidehunter_blubber"
		"10"		"special_bonus_unique_tidehunter_9"
		"11"		"special_bonus_unique_tidehunter_5"
		"12"		"special_bonus_unique_tidehunter_2"
		"13"		"special_bonus_unique_tidehunter_3"
		"14"		"special_bonus_unique_tidehunter_10"
		"15"		"special_bonus_unique_tidehunter"
		"16"		"special_bonus_unique_tidehunter_7"
		"17"		"special_bonus_unique_tidehunter_8"
		}
        "2"
		{
            "1"	"imba_tidehunter_gush"
		"2"	"imba_tidehunter_kraken_shell"
		"3"	"imba_tidehunter_anchor_smash"
		"4"	"imba_tidehunter_coming"//"imba_tidehunter_calling_Maelrawn"
		"5"	"generic_hidden"
		"6"	"imba_tidehunter_ravage"
		"10"	"special_bonus_movement_speed_50"
		"11"	"special_bonus_imba_tidehunter_1"
		"12"	"special_bonus_imba_tidehunter_2"
		"13"	"special_bonus_imba_tidehunter_3"
		"14"	"special_bonus_imba_tidehunter_4"
		"15"	"special_bonus_imba_tidehunter_5"
		"16"	"special_bonus_cooldown_reduction_20"
		//"17"	"special_bonus_attack_damage_200"
		"17"	"special_bonus_imba_tidehunter_8"
		}
		
	}
	"npc_dota_hero_witch_doctor"
	{
		"1"	
        {
            "1"		"witch_doctor_paralyzing_cask"
		"2"		"witch_doctor_voodoo_restoration"
		"3"		"witch_doctor_maledict"
		"4"		"witch_doctor_voodoo_switcheroo"
		"5"		"witch_doctor_gris_gris"
		"6"		"witch_doctor_death_ward"
		"10"		"special_bonus_unique_witch_doctor_4"
		"11"		"special_bonus_hp_200"
		"12"		"special_bonus_unique_witch_doctor_3"
		"13"		"special_bonus_unique_witch_doctor_6"
		"14"		"special_bonus_unique_witch_doctor_1"
		"15"		"special_bonus_unique_witch_doctor_7"
		"16"		"special_bonus_unique_witch_doctor_2"
		"17"		"special_bonus_unique_witch_doctor_5"
		}
        "2"
		{
			"1"		"imba_witch_doctor_paralyzing_cask"
		"2"		"imba_witch_doctor_voodoo_restoration"
		"3"		"imba_witch_doctor_voodoo_switcheroo"
		"4"		"imba_witch_doctor_maledict"
		"5"		"generic_hidden"
		"6"		"imba_witch_doctor_death_ward"
		"10"		"special_bonus_imba_witch_doctor_1"
		"11"		"special_bonus_imba_witch_doctor_2"
		"12"		"special_bonus_imba_witch_doctor_3"
		"13"		"special_bonus_imba_witch_doctor_4"
		"14"		"special_bonus_imba_witch_doctor_5"
		"15"		"special_bonus_imba_witch_doctor_6"
		"16"		"special_bonus_imba_witch_doctor_7"
		"17"		"special_bonus_imba_witch_doctor_8"
		}
		
	}
	"npc_dota_hero_riki"
	{
	
		"1"	
        {
            "1"		"riki_smoke_screen"
		"2"		"riki_blink_strike"
		"3"		"riki_tricks_of_the_trade"
		"4"		"riki_innate_backstab"
		"5"		"generic_hidden"
		"6"		"riki_backstab"
		"10"		"special_bonus_unique_riki_7"
		"11"		"special_bonus_unique_riki_8"
		"12"		"special_bonus_unique_riki_2"
		"13"		"special_bonus_unique_riki_3"
		"14"		"special_bonus_unique_riki_1"
		"15"		"special_bonus_unique_riki_9"
		"16"		"special_bonus_unique_riki_6"
		"17"		"special_bonus_unique_riki_5"
		}
        "2"
		{
            "1"	"imba_riki_smoke_screen"
		"2"	"imba_riki_blink_strike"
		"3"	"imba_riki_tricks_of_the_trade"
		"4"	"imba_riki_poison_dart"
		"5"	"generic_hidden"
		"6"	"imba_riki_backstab"
		"7"	"imba_riki_mode_switch"
		"10"	"special_bonus_attack_damage_35"
		"11"	"special_bonus_attack_speed_25"
		"12"	"special_bonus_imba_riki_4"
		"13"	"special_bonus_imba_riki_1"
		"14"	"special_bonus_imba_riki_2"
		"15"	"special_bonus_imba_riki_3"
		"16"	"special_bonus_imba_riki_6"
		"17"	"special_bonus_imba_riki_5"
		"8"	""
		"9"	""
		}

	}
	"npc_dota_hero_enigma"
	{
		
		"1"	{
            "1"		"enigma_malefice"
		"2"		"enigma_demonic_conversion"
		"3"		"enigma_midnight_pulse"
		"4"		"enigma_gravity_well"
		"5"		"generic_hidden"
		"6"		"enigma_black_hole"
		"10"		"special_bonus_unique_enigma_4"
		"11"		"special_bonus_unique_enigma_6"
		"12"		"special_bonus_hp_250"
		"13"		"special_bonus_unique_enigma_5"
		"14"		"special_bonus_unique_enigma_9"
		"15"		"special_bonus_unique_enigma_3"
		"16"		"special_bonus_unique_enigma_2"
		"17"		"special_bonus_unique_enigma"
		
		}
"2"
		{
			"1"		"malefice"//"enigma_malefice"
		"2"		"demonic_conversion"//"enigma_demonic_conversion"
		"3"		"midnight_pulse"//"enigma_midnight_pulse"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"black_hole"	//"enigma_black_hole"
		"10"		"special_bonus_enigma_1"
		"11"		"special_bonus_enigma_2"
		"12"		"special_bonus_enigma_3"
		"13"		"special_bonus_enigma_4"
		"14"		"special_bonus_custom_value_cd10"
		"15"		"special_bonus_custom_value_ap15"
		"16"		"special_bonus_custom_value_armor10"
		"17"		"special_bonus_custom_value_castrange150"
		}
		
	}
	"npc_dota_hero_tinker"
	{
		
		"1"	{"1"		"tinker_laser"
		"2"		"tinker_march_of_the_machines"
		"3"		"tinker_defense_matrix"
		"4"		"tinker_warp_grenade"
		"5"		"tinker_keen_teleport"
		"6"		"tinker_rearm"
		"7"		"tinker_eureka"
		"10"		"special_bonus_unique_tinker_march_duration"
		"11"		"special_bonus_mana_reduction_8"
		"12"		"special_bonus_unique_tinker_7"
		"13"		"special_bonus_unique_tinker_4"
		"14"		"special_bonus_unique_tinker_defense_matrix_status_resistance"
		"15"		"special_bonus_unique_tinker_5"
		"16"		"special_bonus_unique_tinker"
		"17"		"special_bonus_unique_tinker_rearm_magic_resistance"
		
		}
"2"
		{
            "1"		"tinker_laser"
		"2"		"tinker_heat_seeking_missile"
		"3"		"tinker_defense_matrix"
		"4"		"generic_hidden"
		"5"		"tinker_keen_teleport"
		"6"		"rearm"
		"10"		"special_bonus_spell_amplify_8"
		"11"		"special_bonus_exp_boost_15"
		"12"		"special_bonus_cast_range_125"
		"13"		"special_bonus_mana_reduction_9"
		"14"		"special_bonus_armor_8"
		"15"		"special_bonus_movement_speed_75"
		"16"		"special_bonus_unique_tinker"
		"17"		"special_bonus_unique_tinker_3"
		}
		
	}
	"npc_dota_hero_sniper"
	{
		
		"1"	
        {
            "1"		"sniper_shrapnel"
		"2"		"sniper_headshot"
		"3"		"sniper_take_aim"
		"4"		"sniper_concussive_grenade"
		"5"		"sniper_keen_scope"
		"6"		"sniper_assassinate"
		"10"		"special_bonus_unique_sniper_5"
		"11"		"special_bonus_unique_sniper_headshot_damage"
		"12"		"special_bonus_attack_speed_30"
		"13"		"special_bonus_unique_sniper_4"
		"14"		"special_bonus_unique_sniper_take_aim_armor"
		"15"		"special_bonus_attack_range_100"
		"16"		"special_bonus_unique_sniper_2"
		"17"		"special_bonus_unique_sniper_3"
		}
        "2"
        {
            "HasScepterAndShard"    "1"
            "Author"
            {
                "name"      "特种兵"
                "tip"       "<br>更加全能与多样化"
                "portrait"  ""
            }
            "1"		    "slug"
            "2"		   "sniper_roll"
            "3"		     "one_shot"
            "4"		  "sniper_concussive_grenade"
            "5"		    "generic_hidden"
            "6"		    "grenade"
            "10"		"special_bonus_sniper_10r"
            "11"		"special_bonus_sniper_10l"
            "12"		"special_bonus_sniper_15r"
            "13"		"special_bonus_sniper_15l"
            "14"		"special_bonus_sniper_20r"
            "15"		"special_bonus_sniper_20l"
            "16"		"special_bonus_sniper_25r"
            "17"		"special_bonus_sniper_25l"
        }
        "3"
        {
             "HasScepterAndShard"    "0"
            "Author"
            {
                "name"      "阴间人"
                "tip"       "<br>阴间小王子 <br><br>有a杖魔晶"
                "portrait"  ""
            }
            "1"		    "assassinate"
            "2"		   "ghillie_suit"
            "3"		     "bait"
            "4"		    "yinjianren"
            "5"		    "generic_hidden"
            "6"		    "charlie"
            "10"		"special_bonus_custom_value_msp30"
            "11"		"special_bonus_custom_value_all15"
            "12"		"special_bonus_custom_value_castrange100"
            "13"		"special_bonus_attack_damage_60"
            "14"		"special_bonus_custom_value_ap15"
            "15"		"special_bonus_custom_value_cd10"
            "16"		"special_bonus_attack_speed_160"
            "17"		"special_bonus_attack_range_150"
        }
        "4"
        {
             "HasScepterAndShard"    "0"
            "Author"
            {
                "name"      "伏击者"
                "tip"       "<br>伏地魔本尊 <br><br>暂不支持A杖和魔晶"
                "portrait"  ""
            }
            "1"		    "down"
            "2"		   "run"
            "3"		   "smoke_bomb"
            "4"		   "ambush_man"
            "5"		    "generic_hidden"
            "6"		    "ambush_kill"
            "10"		"special_bonus_custom_value_msp30"
            "11"		"special_bonus_custom_value_all15"
            "12"		"special_bonus_custom_value_castrange100"
            "13"		"special_bonus_attack_range_100"
            "14"		"special_bonus_custom_value_ap15"
            "15"		"special_bonus_custom_value_cd10"
            "16"		"special_bonus_attack_speed_160"
            "17"		"special_bonus_attack_damage_150"
        }
        "5"
        {
             "HasScepterAndShard"    "0"
            "Author"
            {
                "name"      "科学狂人"
                "tip"       "<br>要比就比激光雨 <br><br>暂不支持A杖和魔晶"
                "portrait"  ""
            }
            "1"		    "laser_gun"
            "2"		   "laser_cannon"
            "3"		   "laser_grenade"
            "4"		   "generic_hidden"
            "5"		    "generic_hidden"
            "6"		    "power_surge"
            "10"		"special_bonus_custom_value_msp30"
            "11"		"special_bonus_custom_value_all15"
            "12"		"special_bonus_custom_value_castrange100"
            "13"		"special_bonus_attack_range_200"
            "14"		"special_bonus_custom_value_ap15"
            "15"		"special_bonus_custom_value_cd10"
            "16"		"special_bonus_attack_speed_160"
            "17"		"special_bonus_attack_damage_150"
        }
        "6"
        {
             "HasScepterAndShard"    "0"
            "Author"
            {
                "name"      "怪物杀手"
                "tip"       "<br>把他们全都鲨了 <br><br>暂不支持A杖和魔晶"
                "portrait"  ""
            }
            "1"		    "monster_killer_holy_water_bullet"
            "2"		   "monster_killer_fury_spring"
            "3"		   "monster_killer_pneumatic_crossbow"
            "4"		   "monster_killer_incendiary_grenade"
            "5"		    "monster_killer_witch_potion"
            "6"		    "monster_killer_shapeshift"
            "10"		"special_bonus_custom_value_msp30"
            "11"		"special_bonus_custom_value_all15"
            "12"		"special_bonus_custom_value_castrange100"
            "13"		"special_bonus_attack_range_100"
            "14"		"special_bonus_custom_value_ap15"
            "15"		"special_bonus_custom_value_cd10"
            "16"		"special_bonus_attack_speed_160"
            "17"		"special_bonus_attack_damage_150"
        }
	}
	"npc_dota_hero_necrolyte"
    {

		"1"	{
            "1"		"necrolyte_death_pulse"
		"2"		"necrolyte_ghost_shroud"
		"3"		"necrolyte_heartstopper_aura"
		"4"		"necrolyte_death_seeker"
		"5"		"necrolyte_sadist"
		"6"		"necrolyte_reapers_scythe"
		"10"		"special_bonus_unique_necrophos_6"
		"11"		"special_bonus_unique_necrophos_heartstopper_regen_duration"
		"12"		"special_bonus_unique_necrophos_3"
		"13"		"special_bonus_unique_necrophos_4"
		"14"		"special_bonus_unique_necrophos_sadist_heal_bonus"
		"15"		"special_bonus_unique_necrophos_5"
		"16"		"special_bonus_unique_necrophos_2"
		"17"		"special_bonus_unique_necrophos"
		
		}
        "2"
		{
				"1"	"dlnec_dpulse"
				"2"	"necrolyte_ghost_shroud"
				"3"	"dlnec_haura"
				"4"	"necrolyte_death_seeker"
				"5"	"generic_hidden"
				"6"	"dlnec_reaper"
				"7"	"dlnec_dabyss"
				"8"	"necrolyte_death_pulse"
				"10"	"special_bonus_intelligence_20"	//10r
				"11"	"special_bonus_strength_20" //10l
				"12"	"special_bonus_spell_amplify_15" //15r
				"13"	"special_bonus_magic_resistance_20" //15l
				"14"	"special_bonus_dlnec_20r" //20r	死亡脉冲智力伤害系数+1
				"15"	"special_bonus_dlnec_20l" //20l	竭心光环基础每秒生命流失+2%
				"16"	"special_bonus_dlnec_25r" //25r	死亡镰刀每层增加复活时间+2
				"17"	"special_bonus_dlnec_25l" //20l	死亡镰刀CD减少30秒
		}
	
	}
	"npc_dota_hero_warlock"
	{
		"1"	
        {
            "1"		"warlock_fatal_bonds"
		"2"		"warlock_shadow_word"
		"3"		"warlock_upheaval"
		"4"		"warlock_eldritch_summoning"
		"5"		"generic_hidden"
		"6"		"warlock_rain_of_chaos"
		"10"		"special_bonus_unique_warlock_5"
		"11"		"special_bonus_unique_warlock_upheaval_aoe"
		"12"		"special_bonus_unique_warlock_10"
		"13"		"special_bonus_unique_warlock_7"
		"14"		"special_bonus_unique_warlock_4"
		"15"		"special_bonus_unique_warlock_3"
		"16"		"special_bonus_unique_warlock_2"
		"17"		"special_bonus_unique_warlock_1"
		}

	}
	"npc_dota_hero_beastmaster"
	{
		
		"1"	{
            "1"		"beastmaster_wild_axes"
		"2"		"beastmaster_call_of_the_wild_boar"
		"3"		"beastmaster_call_of_the_wild_hawk"
		"4"		"beastmaster_inner_beast"
		"5"		"beastmaster_drums_of_slom"
		"6"		"beastmaster_primal_roar"
		"7"		"generic_hidden"
		"10"		"special_bonus_unique_beastmaster_3"
		"11"		"special_bonus_unique_beastmaster_9"
		"12"		"special_bonus_unique_beastmaster_5"
		"13"		"special_bonus_unique_beastmaster_4"
		"14"		"special_bonus_unique_beastmaster_2"
		"15"		"special_bonus_unique_beastmaster_6"
		"16"		"special_bonus_unique_beastmaster_wild_axe_cooldown"
		"17"		"special_bonus_unique_beastmaster_7"
		}
        "2"
		{
			
		"1"		"imba_beastmaster_wild_axes"
		"2"		"imba_beastmaster_call_of_the_wild"
		"3"		"imba_beastmaster_call_of_the_wild_hawk"
		"4"		"imba_beastmaster_inner_beast"
		"5"		"generic_hidden"
		"6"		"imba_beastmaster_primal_roar"

		"10"		"special_bonus_imba_beastmaster_3"
		"11"		"special_bonus_imba_beastmaster_8"
		"12"		"special_bonus_imba_beastmaster_7"
		"13"		"special_bonus_imba_beastmaster_1"
		"14"		"special_bonus_imba_beastmaster_2"
		"15"		"special_bonus_imba_beastmaster_4"
		"16"		"special_bonus_imba_beastmaster_5"
		"17"		"special_bonus_imba_beastmaster_6"
		}
		
	}
	"npc_dota_hero_queenofpain"
	{
	
		"1"	{
        "1"		"queenofpain_shadow_strike"
		"2"		"queenofpain_blink"
		"3"		"queenofpain_scream_of_pain"
		"4"		"queenofpain_bondage"
		"5"		"generic_hidden"
		"6"		"queenofpain_sonic_wave"
		"10"		"special_bonus_attack_damage_20"
		"11"		"special_bonus_strength_8"
		"12"		"special_bonus_unique_queen_of_pain_4"
		"13"		"special_bonus_unique_queen_of_pain_1"
		"14"		"special_bonus_unique_queen_of_pain_2"
		"15"		"special_bonus_unique_queen_of_pain_3"
		"16"		"special_bonus_unique_queen_of_pain_6"
		"17"		"special_bonus_unique_queen_of_pain_7"

		}
        "2"
		{
			"1"	"imba_queenofpain_shadow_strike"
		"2"	"imba_queenofpain_blink"
		"3"	"imba_queenofpain_scream_of_pain"
		"4"	"imba_queenofpain_delightful_torment"
		//"4"	"generic_hidden"
		"5"	"generic_hidden"
		"6"	"imba_queenofpain_sonic_wave"
		"10""special_bonus_custom_value_asp30"
		"11"	"special_bonus_imba_queenofpain_4"
		"12"	"special_bonus_custom_value_cd10"
		"13"	"special_bonus_custom_value_ap15"
		"14"	"special_bonus_custom_value_mgr20"
		//"15""special_bonus_custom_value_armor10"
		"15"	"special_bonus_imba_queenofpain_2"
		"16"	"special_bonus_imba_queenofpain_3"
		"17"	"special_bonus_imba_queenofpain_1"


		}

	}
	"npc_dota_hero_venomancer"
	{
		"1"	{
            "1"		"venomancer_venomous_gale"
		"2"		"venomancer_poison_sting"
		"3"		"venomancer_plague_ward"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"venomancer_noxious_plague"
		"10"		"special_bonus_unique_venomancer_3"
		"11"		"special_bonus_unique_venomancer_poisonsting_regen_reduction"
		"12"		"special_bonus_unique_venomancer_8"
		"13"		"special_bonus_unique_venomancer_2"
		"14"		"special_bonus_unique_venomancer_4"
		"15"		"special_bonus_unique_venomancer_gale_plagueward"
		"16"		"special_bonus_unique_venomancer_5"
		"17"		"special_bonus_unique_venomancer"
		
		}
"2"
		{
			"1"		"venomous_gale"
		"2"		"poison_sting"
		"3"		"plague_ward"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"poison_nova"
		"10"		"special_bonus_venomancer_1"
		"11"		"special_bonus_venomancer_6"
		"12"		"special_bonus_venomancer_2"
		"13"		"special_bonus_venomancer_3"
		"14"		"special_bonus_venomancer_4"
		"15"		"special_bonus_venomancer_5"
		"16"		"special_bonus_venomancer_7"
		"17"		"special_bonus_venomancer_8"
		}
		
	}
	"npc_dota_hero_faceless_void"
	{
	
		"1"	
        {
            "1"		"faceless_void_time_walk"
		"2"		"faceless_void_time_dilation"	
		"3"		"faceless_void_time_lock"
		"4"		"faceless_void_time_walk_reverse"
		"5"		"faceless_void_distortion_field"
		"6"		"faceless_void_chronosphere"
		"10"		"special_bonus_unique_faceless_void_6"
		"11"		"special_bonus_unique_faceless_void_7"
		"12"		"special_bonus_unique_faceless_void_3"
		"13"		"special_bonus_unique_faceless_void_8"
		"14"		"special_bonus_unique_faceless_void"
		"15"		"special_bonus_unique_faceless_void_5"
		"16"		"special_bonus_unique_faceless_void_4"
		"17"		"special_bonus_unique_faceless_void_2"

		}
        "2"
		{
			"1"		"imba_faceless_void_time_walk"
		"2"		"imba_faceless_void_time_dilation"	
		"3"		"imba_faceless_void_time_lock"
		"4"		"generic_hidden"
		"5"		"faceless_void_backtrack"
		"6"		"imba_faceless_void_chronosphere"
		"10"		"special_bonus_imba_faceless_void_7"
		"11"		"special_bonus_imba_faceless_void_8"
		"12"		"special_bonus_imba_faceless_void_2"
		"13"		"special_bonus_imba_faceless_void_3"
		"14"		"special_bonus_attack_speed_40"
		"15"		"special_bonus_imba_faceless_void_4"
		"16"		"special_bonus_imba_faceless_void_6"
		"17"		"special_bonus_imba_faceless_void_5"
		}
	}
	"npc_dota_hero_skeleton_king"
	{
		"1"	{
            "1"		"skeleton_king_hellfire_blast"
		"2"		"generic_hidden"
		"3"		"skeleton_king_mortal_strike"
		"4"		"skeleton_king_vampiric_spirit"
		"5"		"generic_hidden"
		"6"		"skeleton_king_reincarnation"
		"10"		"special_bonus_unique_wraith_king_2"
		"11"		"special_bonus_unique_wraith_king_3"
		"12"		"special_bonus_unique_wraith_king_11"
		"13"		"special_bonus_hp_400"
		"14"		"special_bonus_cleave_35"
		"15"		"special_bonus_attack_speed_70"
		"16"		"special_bonus_unique_wraith_king_10"
		"17"		"special_bonus_unique_wraith_king_4"

		}
        "2"
		{
        "1"		"hellfire_blast"
		"2"		"vampiric_aura"
		"3"		"mortal_strike"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"reincarnation"
		"10"		"special_bonus_skeleton_king_1"
		"11"		"special_bonus_skeleton_king_2"
		"12"		"special_bonus_skeleton_king_3"
		"13"		"special_bonus_skeleton_king_4"
		"14"		"special_bonus_skeleton_king_5"
		"15"		"special_bonus_skeleton_king_6"
		"16"		"special_bonus_skeleton_king_7"
		"17"		"special_bonus_skeleton_king_8"
		}

	}
	"npc_dota_hero_death_prophet"
	{
		"1"	{
            "1"		"death_prophet_carrion_swarm"
		"2"		"death_prophet_silence"
		"3"		"death_prophet_spirit_siphon"
		"4"		"death_prophet_witchcraft"
		"5"		"generic_hidden"
		"6"		"death_prophet_exorcism"
		"10"		"special_bonus_attack_speed_40"
		"11"		"special_bonus_magic_resistance_12"
		"12"		"special_bonus_hp_250"
		"13"		"special_bonus_unique_death_prophet_2"
		"14"		"special_bonus_unique_death_prophet_crypt_swarm_damage"
		"15"		"special_bonus_unique_death_prophet_3"
		"16"		"special_bonus_unique_death_prophet_5"
		"17"		"special_bonus_unique_death_prophet"
		
		}
        "2"
		{
			
			"1"	"imba_death_prophet_carrion_swarm"
		"2"	"imba_death_prophet_silence"
		"3"	"imba_death_prophet_spirit_siphon"
		"4"	"imba_death_prophet_witchcraft"
		"5"	"generic_hidden"
		"6"	"imba_death_prophet_exorcism"
		"10"	"special_bonus_attack_damage_40"
		"11"	"special_bonus_magic_resistance_25"
		"12"	"special_bonus_imba_death_prophet_3"
		"13"	"special_bonus_attack_speed_100"
		"14"	"special_bonus_hp_800"
		"15"	"special_bonus_imba_death_prophet_2"
		"16"	"special_bonus_movement_speed_percentage_10"
		"17"	"special_bonus_unique_death_prophet"
		"7"	""
		"8"	""
		"9"	""
		}
		
	}
	"npc_dota_hero_phantom_assassin"
	{
	
		"1"	{
            "1"		"phantom_assassin_stifling_dagger"
		"2"		"phantom_assassin_phantom_strike"
		"3"		"phantom_assassin_blur"
		"4"		"phantom_assassin_fan_of_knives"
		"5"		"phantom_assassin_immaterial"
		"6"		"phantom_assassin_coup_de_grace"
		"10"		"special_bonus_unique_phantom_assassin_4"
		"11"		"special_bonus_unique_phantom_assassin_7"
		"12"		"special_bonus_unique_phantom_assassin_3"
		"13"		"special_bonus_unique_phantom_assassin_6"
		"14"		"special_bonus_unique_phantom_assassin_5"
		"15"		"special_bonus_unique_phantom_assassin_strike_aspd"
		"16"		"special_bonus_unique_phantom_assassin_2"
		"17"		"special_bonus_unique_phantom_assassin"
		}
        "2"
		{
			"1"		"stifling_dagger"//"phantom_assassin_stifling_dagger"
		"2"		"phantom_strike"//"phantom_assassin_phantom_strike"
		"3"		"blur"//"phantom_assassin_blur"
		"4"		"phantom_assassin_fan_of_knives"
		"5"		"generic_hidden"
		"6"		"coup_de_grace"//"phantom_assassin_coup_de_grace"
		"10"		"special_bonus_unique_imba_phantom_assassin_1" 
		"11"		"special_bonus_unique_imba_phantom_assassin_2"
		"12"		"special_bonus_phantom_assassin_3"
		"13"		"special_bonus_phantom_assassin_4"
		"14"		"special_bonus_phantom_assassin_5"
		"15"		"special_bonus_phantom_assassin_6"
		"16"		"special_bonus_phantom_assassin_7"
		"17"		"special_bonus_phantom_assassin_8"

		}
	}
	"npc_dota_hero_pugna"
	{
		"1"	{
            "1"		"pugna_nether_blast"
		"2"		"pugna_decrepify"
		"3"		"pugna_nether_ward"
		"4"		"pugna_oblivion_savant"
		"5"		"generic_hidden"
		"6"		"pugna_life_drain"
		"10"		"special_bonus_unique_pugna_decrepify_ally_movespeed"
		"11"		"special_bonus_hp_200"
		"12"		"special_bonus_unique_pugna_4"
		"13"		"special_bonus_unique_pugna_6"
		"14"		"special_bonus_unique_pugna_1"
		"15"		"special_bonus_unique_pugna_5"
		"16"		"special_bonus_unique_pugna_2"
		"17"		"special_bonus_unique_pugna_3"
		
		}
		"2"
		{
			"1"	"imba_pugna_nether_blast"
		"2"	"imba_pugna_decrepify"
		"3"	"pugna_nether_ward"
		"4"	"imba_pugna_life_drain_end"
		"5"	"generic_hidden"
		"6"	"imba_pugna_life_drain"
		"10"	"special_bonus_movement_speed_15"
		"11"	"special_bonus_hp_175"
		"12"	"special_bonus_imba_pugna_1"
		"13"	"special_bonus_unique_pugna_6"
		"14"	"special_bonus_imba_pugna_3"
		"15"	"special_bonus_spell_lifesteal_20"
		"16"	"special_bonus_imba_pugna_5"
		"17"	"special_bonus_unique_pugna_3"
		}
	}
	"npc_dota_hero_templar_assassin"
	{
		"1"	{
            "1"		"templar_assassin_refraction"
		"2"		"templar_assassin_meld"
		"3"		"templar_assassin_psi_blades"
		"4"		"templar_assassin_trap"
		"5"		"templar_assassin_trap_teleport"
		"6"		"templar_assassin_psionic_trap"
		"10"		"special_bonus_unique_templar_assassin_refraction_damage"
		"11"		"special_bonus_unique_templar_assassin_3"
		"12"		"special_bonus_unique_templar_assassin_refraction_disable_cast"
		"13"		"special_bonus_unique_templar_assassin_8"
		"14"		"special_bonus_unique_templar_assassin_4"
		"15"		"special_bonus_unique_templar_assassin_2"
		"16"		"special_bonus_unique_templar_assassin_7"
		"17"		"special_bonus_unique_templar_assassin"
		
		}
"2"
		{
			"1"		"refraction"
		"2"		"meld"
		"3"		"psi_blades"
		"4"		"assassin_trap"
		"5"		"trap_teleport"
		"6"		"psionic_trap"
		"10"	"special_bonus_templar_assassin_1"
		"11"	"special_bonus_templar_assassin_2"
		"12"	"special_bonus_templar_assassin_3"
		"13"	"special_bonus_templar_assassin_4"
		"14"	"special_bonus_templar_assassin_5"
		"15"	"special_bonus_templar_assassin_6"
		"16"	"special_bonus_templar_assassin_7"
		"17"	"special_bonus_templar_assassin_8"
		}
		
	}
	"npc_dota_hero_viper"
	{
		"1"	{
            "1"		"viper_poison_attack"
		"2"		"viper_nethertoxin"
		"3"		"viper_corrosive_skin"
		"4"		"viper_nose_dive"
		"5"		"generic_hidden"
		"6"		"viper_viper_strike"
		"10"		"special_bonus_unique_viper_4"
		"11"		"special_bonus_unique_viper_1"
		"12"		"special_bonus_unique_viper_3"
		"13"		"special_bonus_unique_viper_6"
		"14"		"special_bonus_unique_viper_2"
		"15"		"special_bonus_unique_viper_7"
		"16"		"special_bonus_unique_viper_5"
		"17"		"special_bonus_unique_viper_8"
		}
		"2"		
		{
			"1"		"poison_attack"
		"2"		"nethertoxin"
		"3"		"corrosive_skin"
		"4"		"viper_nose_dive"
		"5"		"generic_hidden"
		"6"		"viper_strike"
		"10"		"special_bonus_viper_1"
		"11"		"special_bonus_viper_2"
		"12"		"special_bonus_custom_value_asp50"
		"13"		"special_bonus_viper_3"
		"14"		"special_bonus_viper_4"
		"15"		"special_bonus_viper_5"
		"16"		"special_bonus_viper_7"
		"17"		"special_bonus_custom_value_str40"
		}
	}
	"npc_dota_hero_luna"
	{
		"1"	{
            "1"		"luna_lucent_beam"
		"2"		"luna_moon_glaive"
		"3"		"luna_lunar_blessing"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"luna_eclipse"
		"7"		"luna_selemenes_favor"
		"10"		"special_bonus_unique_luna_7"
		"11"		"special_bonus_unique_luna_4"
		"12"		"special_bonus_unique_luna_1"
		"13"		"special_bonus_unique_luna_6"
		"14"		"special_bonus_unique_luna_8"
		"15"		"special_bonus_unique_luna_2"
		"16"		"special_bonus_unique_luna_3"
		"17"		"special_bonus_unique_luna_5"

		}
        "2"
		{
			"1"		"imba_luna_lucent_beam"
		"2"		"imba_luna_moon_glaive"
		"3"		"imba_luna_lunar_blessing"
		"4"		"imba_luna_lunar_grace"
		"5"		"generic_hidden"
		"6"		"imba_luna_eclipse"
		"10"		"special_bonus_imba_luna_1"
		"11"		"special_bonus_imba_luna_3"
		"12"		"special_bonus_imba_luna_2"
		"13"		"special_bonus_imba_luna_4"
		"14"		"special_bonus_imba_luna_5"
		"15"		"special_bonus_imba_luna_6"
		"16"		"special_bonus_imba_luna_7"
		"17"		"special_bonus_imba_luna_8"
		}

	}
	"npc_dota_hero_dragon_knight"
	{
		"1"	{
            "1"		"dragon_knight_breathe_fire"
		"2"		"dragon_knight_dragon_tail"
		"3"		"dragon_knight_dragon_blood"
		"4"		"dragon_knight_fireball"
		"5"		"generic_hidden"
		"6"		"dragon_knight_elder_dragon_form"
		"7"		"dragon_knight_inherited_vigor"
		"10"		"special_bonus_attack_damage_15"
		"11"		"special_bonus_unique_dragon_knight_3"
		"12"		"special_bonus_unique_dragon_knight_2"
		"13"		"special_bonus_hp_300"
		"14"		"special_bonus_unique_dragon_knight_7"
		"15"		"special_bonus_unique_dragon_knight_9"
		"16"		"special_bonus_unique_dragon_knight"
		"17"		"special_bonus_unique_dragon_knight_8"
		}
"2"
		{
			"1"		"breathe_fire"
		"2"		"dragon_tail"
		"3"		"dragon_blood"
		"4"		"dragon_knight_fireball"
		"5"		"generic_hidden"
		"6"		"elder_dragon_form"
		"10"		"special_bonus_dragon_knight_1"
		"11"		"special_bonus_dragon_knight_2"
		"12"		"special_bonus_dragon_knight_3"
		"13"		"special_bonus_dragon_knight_4"
		"14"		"special_bonus_dragon_knight_5"
		"15"		"special_bonus_dragon_knight_6"
		"16"		"special_bonus_dragon_knight_7"
		"17"		"special_bonus_dragon_knight_8"
		}
	}
	"npc_dota_hero_dazzle"
	{
		"1"	{
                "1"		"dazzle_poison_touch"
            "2"		"dazzle_shallow_grave"
            "3"		"dazzle_shadow_wave"
            "4"		"dazzle_innate_weave"
            "5"		"generic_hidden"
            "6"		"dazzle_bad_juju"
            "10"		"special_bonus_unique_dazzle_poison_touch_attack_range_bonus"
            "11"		"special_bonus_mp_regen_175"
            "12"		"special_bonus_unique_dazzle_2"
            "13"		"special_bonus_attack_speed_80"
            "14"		"special_bonus_unique_dazzle_5"
            "15"		"special_bonus_unique_dazzle_3"
            "16"		"special_bonus_unique_dazzle_1"
            "17"		"special_bonus_unique_dazzle_4"
		}
        "2"
		{
            "1"	"imba_dazzle_poison_touch"
            "2"	"imba_dazzle_shallow_grave"
            "3"	"imba_dazzle_shadow_wave"
            "4"	"imba_dazzle_help"
            "5"	"generic_hidden"
            "6"	"imba_dazzle_weave"
            "10"	"special_bonus_mp_regen_5"
            "11"	"special_bonus_movement_speed_15"
            "12"	"special_bonus_imba_dazzle_1"
            "13"	"special_bonus_imba_dazzle_5"
            "14"	"special_bonus_imba_dazzle_2"
            "15"	"special_bonus_imba_dazzle_6"
            "16"	"special_bonus_imba_dazzle_4"
            "17"	"special_bonus_imba_dazzle_3"
            "7"	""
            "8"	""
            "9"	""
		}

	}
	"npc_dota_hero_rattletrap"
	{
	
		"1"	{
            "1"		"rattletrap_battery_assault"
		"2"		"rattletrap_power_cogs"
		"3"		"rattletrap_rocket_flare"
		"4"		"rattletrap_overclocking"
		"5"		"rattletrap_jetpack"
		"6"		"rattletrap_hookshot"
		"7"		"rattletrap_armor_power"
		"10"		"special_bonus_unique_clockwerk_7"
		"11"		"special_bonus_unique_clockwerk_9"
		"12"		"special_bonus_unique_clockwerk_5"
		"13"		"special_bonus_unique_clockwerk_3"
		"14"		"special_bonus_unique_clockwerk_4"
		"15"		"special_bonus_unique_clockwerk_flare_damage"
		"16"		"special_bonus_unique_clockwerk_6"
		"17"		"special_bonus_unique_clockwerk"
		
		}
"2"
		{
			"1"	"imba_rattletrap_battery_assault"
		"2"	"imba_rattletrap_power_cogs"
		"3"	"imba_rattletrap_rocket_flare"
		"4"	"imba_rattletrap_hookshot_stop"
		"5"	"rattletrap_jetpack"
		"6"	"imba_rattletrap_hookshot"
		"10"	"special_bonus_armor_6"
		"11"	"special_bonus_movement_speed_30"
		"12"	"special_bonus_mp_regen_10"
		"13"	"special_bonus_attack_speed_30"
		"14"	"special_bonus_imba_rattletrap_3"
		"15"	"special_bonus_hp_400"
		"16"	"special_bonus_imba_rattletrap_4"
		"17"	"special_bonus_imba_rattletrap_2"
		}
		
	}
	"npc_dota_hero_leshrac"
	{
		
		"1"	
        {"1"		"leshrac_split_earth"
		"2"		"leshrac_diabolic_edict"
		"3"		"leshrac_lightning_storm"
		"4"		"leshrac_greater_lightning_storm"
		"5"		"leshrac_defilement"
		"6"		"leshrac_pulse_nova"
		"10"		"special_bonus_mp_regen_150"
		"11"		"special_bonus_armor_4"
		"12"		"special_bonus_unique_leshrac_6"
		"13"		"special_bonus_unique_leshrac_7"
		"14"		"special_bonus_unique_leshrac_4"
		"15"		"special_bonus_unique_leshrac_3"
		"16"		"special_bonus_unique_leshrac_pulse_nova_lightning"
		"17"		"special_bonus_unique_leshrac_1"
		}
        "2"
		{
			"1"		"imba_leshrac_split_earth"
		"2"		"imba_leshrac_diabolic_edict"
		"3"		"imba_leshrac_lightning_storm"
		"4"		"generic_hidden"
		"5"		"imba_leshrac_greater_lightning_storm" //虚无主义
		"6"		"imba_leshrac_pulse_nova"

		
		"10"		"special_bonus_mp_600"
		"11"		"special_bonus_imba_leshrac_1"      //+100撕裂大地范围
		"12"		"special_bonus_imba_leshrac_2"        //+2闪电跳跃次数
		"13"		"special_bonus_imba_leshrac_3"      //+1s闪电风暴减速
		"14"		"special_bonus_imba_leshrac_4"      //+100脉冲新星范围
		"15"		"special_bonus_imba_leshrac_5"      //+100脉冲新星伤害
		"16"		"special_bonus_imba_leshrac_6"   //+5s恶魔敕令持续时间
		"17"		"special_bonus_imba_leshrac_7"    //+20恶魔敕令爆炸次数


		"7"	   "imba_leshrac_tormented_soul"  //
		"8"	   ""
		"9"	   ""
		}
	}
	"npc_dota_hero_furion"
	{
		"1"	{
            "1"		"furion_sprout"
		"2"		"furion_teleportation"
		"3"		"furion_force_of_nature"
		"4"		"furion_curse_of_the_forest"
		"5"		"furion_spirit_of_the_forest"
		"6"		"furion_wrath_of_nature"
		"10"		"special_bonus_unique_furion_6"
		"11"		"special_bonus_unique_furion_5"
		"12"		"special_bonus_unique_furion_2"
		"13"		"special_bonus_unique_furion_teleportation_barrier"
		"14"		"special_bonus_unique_furion_7"
		"15"		"special_bonus_unique_furion_4"
		"16"		"special_bonus_unique_furion_3"
		"17"		"special_bonus_unique_furion"
		}
        "2"
		{
		"1"		"sprout"
		"2"		"furion_teleportation"
		"3"		"furion_force_of_nature"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"furion_wrath_of_nature"
		"10"		"special_bonus_attack_damage_20"
		"11"		"special_bonus_unique_furion_5"
		"12"		"special_bonus_attack_speed_25"
		"13"		"special_bonus_unique_furion_2"
		"14"		"special_bonus_armor_8"
		"15"		"special_bonus_cooldown_reduction_20"
		"16"		"special_bonus_unique_furion_3"
		"17"		"special_bonus_unique_furion"
		}
	}
	"npc_dota_hero_life_stealer"
	{
		"1"	
        {
        "1"		"life_stealer_rage"
		"2"		"life_stealer_open_wounds"
		"3"		"life_stealer_ghoul_frenzy"
		"4"		"life_stealer_feast"
		"5"		"generic_hidden"
		"6"		"life_stealer_infest"
		"7"		"life_stealer_consume"
		"10"		"special_bonus_unique_lifestealer_infest_damage"
		"11"		"special_bonus_unique_lifestealer_2"
		"12"		"special_bonus_unique_lifestealer_5"
		"13"		"special_bonus_unique_lifestealer_4"
		"14"		"special_bonus_unique_lifestealer_infest_target_bonus"
		"15"		"special_bonus_unique_lifestealer_6"
		"16"		"special_bonus_unique_lifestealer_3"
		"17"		"special_bonus_unique_lifestealer"
		}
        "2"
		{
			"1"		"imba_life_stealer_rage"
		"2"		"imba_life_stealer_feast"
		"3"		"imba_lifestealer_open_wounds"
		"4"		"imba_life_stealer_ghoul_frenzy"
		"5"		"generic_hidden"
		"6"		"imba_life_stealer_control"
		"7"		"imba_life_stealer_assimilate_eject"
		"8"		"imba_life_stealer_parasite"
		"10"		"special_bonus_imba_life_stealer_1"
		"11"		"special_bonus_imba_life_stealer_8"
		"12"		"special_bonus_imba_life_stealer_2"
		"13"		"special_bonus_imba_life_stealer_7"
		"14"		"special_bonus_imba_life_stealer_6"
		"15"		"special_bonus_imba_life_stealer_5"
		"16"		"special_bonus_imba_life_stealer_3"
		"17"		"special_bonus_imba_life_stealer_4"
		}
	
	}
	"npc_dota_hero_dark_seer"
	{
		
		"1"	{
            "1"		"dark_seer_vacuum"
		"2"		"dark_seer_ion_shell"
		"3"		"dark_seer_surge"
		"4"		"dark_seer_normal_punch"
		"5"		"dark_seer_mental_fortitude"
		"6"		"dark_seer_wall_of_replica"
		"10"		"special_bonus_unique_dark_seer_7"
		"11"		"special_bonus_unique_dark_seer_5"
		"12"		"special_bonus_unique_dark_seer_2"
		"13"		"special_bonus_unique_dark_seer_6"
		"14"		"special_bonus_unique_dark_seer_13"
		"15"		"special_bonus_unique_dark_seer"
		"16"		"special_bonus_unique_dark_seer_14"
		"17"		"special_bonus_unique_dark_seer_3"
		
		}
        "2"
		{
            "1"		"seer_vacuum"
            "2"		"ion_shell"
            "3"		"surge"
            "4"		"dark_seer_normal_punch"
            "5"		"generic_hidden"
            "6"		"seriously_punch"
            "10"	"special_bonus_dark_seer_1"
            "11"	"special_bonus_dark_seer_2"
            "12"	"special_bonus_dark_seer_3"
            "13"	"special_bonus_dark_seer_4"
            "14"	"special_bonus_dark_seer_5"
            "15"	"special_bonus_dark_seer_6"
            "16"	"special_bonus_dark_seer_7"
            "17"	"special_bonus_dark_seer_8"
		}
		
		
	}
	"npc_dota_hero_clinkz"
	{
	
		"1"	{
            "1"		"clinkz_strafe"
		"2"		"clinkz_tar_bomb"
		"3"		"clinkz_death_pact"
		"4"		"clinkz_burning_barrage"
		"5"		"clinkz_burning_army"
		"6"		"clinkz_wind_walk"
		"7"		"clinkz_bone_and_arrow"
		"10"		"special_bonus_unique_clinkz_1"
		"11"		"special_bonus_unique_clinkz_10"
		"12"		"special_bonus_attack_range_75"
		"13"		"special_bonus_unique_clinkz_9"
		"14"		"special_bonus_unique_clinkz_8"
		"15"		"special_bonus_unique_clinkz_7"
		"16"		"special_bonus_unique_clinkz_4"
		"17"		"special_bonus_unique_clinkz_3"
		}
        "2"
		{
		"1"	"imba_clinkz_strafe_searing_arrows"
		"2"	"imba_clinkz_burning_army"
		"3"	"imba_clinkz_wind_walk"
		"4"	"clinkz_burning_barrage"
		"5"	"generic_hidden"
		"6"	"imba_clinkz_death_pact"

		"10"	"special_bonus_imba_clinkz_6"
		"11"	"special_bonus_imba_clinkz_4"
		"12"	"special_bonus_imba_clinkz_3"
		"13"	"special_bonus_imba_clinkz_7"
		"14"	"special_bonus_attack_range_125"
		"15"	"special_bonus_imba_clinkz_5"
		"16"	"special_bonus_imba_clinkz_2"
		"17"	"special_bonus_imba_clinkz_1"
		}
		
	}
	"npc_dota_hero_omniknight"
	{
		
		"1"	{
            "1"		"omniknight_purification"
		"2"		"omniknight_martyr"
		"3"		"omniknight_hammer_of_purity"
		"4"		"omniknight_degen_aura"
		"5"		"generic_hidden"
		"6"		"omniknight_guardian_angel"
		"10"		"special_bonus_unique_omniknight_6"
		"11"		"special_bonus_attack_base_damage_50"
		"12"		"special_bonus_unique_omniknight_2"
		"13"		"special_bonus_unique_omniknight_7"
		"14"		"special_bonus_unique_omniknight_5"
		"15"		"special_bonus_unique_omniknight_3"
		"16"		"special_bonus_unique_omniknight_1"
		"17"		"special_bonus_unique_omniknight_4"
		
		}
    "2"
		{
			"1"		"purification_new"
		"2"		"repel"
		"3"		"hammer_of_purity"
		"4"		"omniknight_degen_aura"
		"5"		"generic_hidden"
		"6"		"guardian_angel_new"
		"10"		"special_bonus_omniknight_1"
		"11"		"special_bonus_omniknight_2"
		"12"		"special_bonus_omniknight_3"
		"13"		"special_bonus_omniknight_4"
		"14"		"special_bonus_omniknight_5"
		"15"		"special_bonus_omniknight_6"
		"16"		"special_bonus_omniknight_7"
		"17"		"special_bonus_omniknight_8"
		}
	
	}
	"npc_dota_hero_enchantress"
	{
		
		"1"	{
            "1"		"enchantress_impetus"
		"2"		"enchantress_enchant"
		"3"		"enchantress_natures_attendants"
		"4"		"enchantress_bunny_hop"
		"5"		"enchantress_little_friends"
		"6"		"enchantress_untouchable"
		"7"		"enchantress_forest_freebie"
		"10"		"special_bonus_unique_enchantress_enchant_armor"
		"11"		"special_bonus_unique_enchantress_6"
		"12"		"special_bonus_attack_damage_45"
		"13"		"special_bonus_unique_enchantress_5"
		"14"		"special_bonus_unique_enchantress_3"
		"15"		"special_bonus_unique_enchantress_enchant_health_damage"
		"16"		"special_bonus_unique_enchantress_4"
		"17"		"special_bonus_unique_enchantress_2"
		
		}
        "2"
		{
			"1"		"impetus"//"enchantress_impetus"
            "2"		"bunny_hop"
            "3"		"natures_attendants"	//"enchantress_natures_attendants"
            "4"		"enchant"//"enchantress_enchant"//"enchantress_bunny_hop"
            "5"		"generic_hidden"
            "6"		"untouchable"//"enchantress_untouchable"
            "10"		"special_bonus_enchantress_1"
            "11"		"special_bonus_enchantress_5"
            "12"		"special_bonus_enchantress_6"
            "13"		"special_bonus_enchantress_4"
            "14"		"special_bonus_enchantress_2"
            "15"		"special_bonus_enchantress_3"
            "16"		"special_bonus_enchantress_7"
            "17"		"special_bonus_enchantress_8"
		}

		
	}
	"npc_dota_hero_huskar"
	{
		"1"	{
            "1"		"huskar_inner_fire"
		"2"		"huskar_burning_spear"
		"3"		"huskar_berserkers_blood"
		"4"		"huskar_blood_magic"
		"5"		"generic_hidden"
		"6"		"huskar_life_break"
		"10"		"special_bonus_unique_huskar_3"
		"11"		"special_bonus_unique_huskar_4"
		"12"		"special_bonus_unique_huskar_2"
		"13"		"special_bonus_lifesteal_15"
		"14"		"special_bonus_unique_huskar_6"
		"15"		"special_bonus_unique_huskar_7"
		"16"		"special_bonus_unique_huskar"
		"17"		"special_bonus_unique_huskar_5"
		}
"2"
		{
			"1"	"imba_huskar_inner_fire"
		"2"	"imba_huskar_burning_spear"
		"3"	"imba_huskar_berserkers_blood"
		"4"	"generic_hidden"
		"5"	"generic_hidden"
		"6"	"imba_huskar_life_break"
		"10"	"special_bonus_imba_huskar_3"
		"11"	"special_bonus_imba_huskar_2"
		"12"	"special_bonus_lifesteal_20"
		"13"	"special_bonus_imba_huskar_1"
		"14"	"special_bonus_imba_huskar_4"
		"15"	"special_bonus_imba_huskar_5"
		"16"	"special_bonus_attack_range_275"
		"17"	"special_bonus_imba_huskar_6"
		}
		
	}
	"npc_dota_hero_night_stalker"
	{
		"1"	{
            "1"		"night_stalker_void"
		"2"		"night_stalker_crippling_fear"
		"3"		"night_stalker_hunter_in_the_night"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"night_stalker_darkness"
		"7"		"night_stalker_heart_of_darkness"
		"10"		"special_bonus_unique_night_stalker_4"
		"11"		"special_bonus_unique_night_stalker_7"
		"12"		"special_bonus_unique_night_stalker_3"
		"13"		"special_bonus_unique_night_stalker_hunter_status_resist"
		"14"		"special_bonus_unique_night_stalker_crippling_fear_damage"
		"15"		"special_bonus_strength_20"
		"16"		"special_bonus_unique_night_stalker_2"
		"17"		"special_bonus_unique_night_stalker"
		}
"2"
		{
			"1"		"void"//"night_stalker_void"
		"2"		"crippling_fear"	//"night_stalker_crippling_fear"
		"3"		"hunter_in_the_night"//"night_stalker_hunter_in_the_night"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"darkness"//"night_stalker_darkness"
		"10"		"special_bonus_night_stalker_1"
		"11"		"special_bonus_night_stalker_2"
		"12"		"special_bonus_night_stalker_3"
		"13"		"special_bonus_night_stalker_4"
		"14"		"special_bonus_night_stalker_5"
		"15"		"special_bonus_night_stalker_6"
		"16"		"special_bonus_night_stalker_7"
		"17"		"special_bonus_night_stalker_8"
		}
	
	}
	"npc_dota_hero_broodmother"
	{
		
		"1"	{
            "1"		"broodmother_insatiable_hunger"
		"2"		"broodmother_spin_web"
		"3"		"broodmother_incapacitating_bite"
		"4"		"broodmother_sticky_snare"
		"5"		"broodmother_spiders_milk"
		"6"		"broodmother_spawn_spiderlings"
		"10"		"special_bonus_unique_broodmother_3"
		"11"		"special_bonus_unique_broodmother_6"
		"12"		"special_bonus_unique_broodmother_5"
		"13"		"special_bonus_unique_broodmother_7"
		"14"		"special_bonus_unique_broodmother_2"
		"15"		"special_bonus_attack_speed_35"
		"16"		"special_bonus_unique_broodmother_1"
		"17"		"special_bonus_unique_broodmother_4"
		
		}
"2"
		{
			"1"	"imba_broodmother_spider_strikes"
		"2"	"imba_broodmother_spin_web"
		"3"	"imba_broodmother_incapacitating_bite"
		"4"	"imba_broodmother_silken_bola"
		"5"	"generic_hidden"
		"6"	"imba_broodmother_insatiable_hunger"

		"10"	"special_bonus_imba_broodmother_8"
		"11"	"special_bonus_imba_broodmother_4"
		"12"	"special_bonus_imba_broodmother_3"
		"13"	"special_bonus_imba_broodmother_5"
		"14"	"special_bonus_imba_broodmother_7"
		"15"	"special_bonus_imba_broodmother_6"
		"16"	"special_bonus_imba_broodmother_2"
		"17"	"special_bonus_imba_broodmother_1"
		}
		
	
	}
	"npc_dota_hero_bounty_hunter"
	{
		
		"1"	{
            "1"		"bounty_hunter_shuriken_toss"
		"2"		"bounty_hunter_jinada"
		"3"		"bounty_hunter_wind_walk"
		"4"		"bounty_hunter_wind_walk_ally"
		"5"		"bounty_hunter_big_game_hunter"
		"6"		"bounty_hunter_track"
		"10"		"special_bonus_unique_bounty_hunter_5"
		"11"		"special_bonus_unique_bounty_hunter_4"
		"12"		"special_bonus_unique_bounty_hunter_9"
		"13"		"special_bonus_unique_bounty_hunter_3"
		"14"		"special_bonus_unique_bounty_hunter_8"
		"15"		"special_bonus_unique_bounty_hunter"
		"16"		"special_bonus_unique_bounty_hunter_2"
		"17"		"special_bonus_unique_bounty_hunter_jinada_no_cooldown"

		}
"2"
		{
			"1"	"imba_bounty_hunter_shuriken_toss"
		"2"	"imba_bounty_hunter_jinada"
		"3"	"imba_bounty_hunter_wind_walk"
		"4"	"imba_bounty_hunter_shadow_jaunt"
		"5"	"generic_hidden"
		"6"	"imba_bounty_hunter_track"
		"10"	"special_bonus_imba_bounty_hunter_2"
		"11"	"special_bonus_imba_bounty_hunter_4"
		"12"	"special_bonus_imba_bounty_hunter_1"
		"13"	"special_bonus_imba_bounty_hunter_3"
		"14"	"special_bonus_imba_bounty_hunter_5"
		"15"	"special_bonus_imba_bounty_hunter_6"
		"16"	"special_bonus_imba_bounty_hunter_7"
		"17"	"special_bonus_imba_bounty_hunter_8"
		}

	
	}
	"npc_dota_hero_weaver"
	{
	
		"1"	
        {
            "1"		"weaver_the_swarm"
		"2"		"weaver_shukuchi"
		"3"		"weaver_geminate_attack"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"weaver_time_lapse"
		"10"		"special_bonus_unique_weaver_1"
		"11"		"special_bonus_strength_8"
		"12"		"special_bonus_mana_break_20"
		"13"		"special_bonus_unique_weaver_4"
		"14"		"special_bonus_unique_weaver_2"
		"15"		"special_bonus_unique_weaver_3"
		"16"		"special_bonus_unique_weaver_6"
		"17"		"special_bonus_unique_weaver_5"
		}
    "2"
		{
			"1"		"weaver_the_swarm"
		"2"		"shukuchi"
		"3"		"weaver_geminate_attack"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"weaver_time_lapse"
		"10"		"special_bonus_unique_imba_weaver_1"
		"11"		"special_bonus_strength_9"
		"12"		"special_bonus_mana_break_20"
		"13"		"special_bonus_unique_weaver_4"
		"14"		"special_bonus_unique_weaver_2"
		"15"		"special_bonus_unique_weaver_3"
		"16"		"special_bonus_unique_imba_weaver_6"
		"17"		"special_bonus_unique_weaver_5"


		}

	
	}
	"npc_dota_hero_jakiro"
	{
		
		"1"	
        {
        
		"1"		"jakiro_dual_breath"
		"2"		"jakiro_ice_path"
		"3"		"jakiro_liquid_fire"
		"4"		"jakiro_liquid_ice"
		"5"		"jakiro_double_trouble"
		"6"		"jakiro_macropyre"
		"10"		"special_bonus_attack_range_200"
		"11"		"special_bonus_unique_jakiro_dualbreath_slow"
		"12"		"special_bonus_unique_jakiro_4"
		"13"		"special_bonus_unique_jakiro_6"
		"14"		"special_bonus_unique_jakiro"
		"15"		"special_bonus_unique_jakiro_7"
		"16"		"special_bonus_unique_jakiro_2"
		"17"		"special_bonus_unique_jakiro_3"
		
		}
    "2"
		{
			"1"		"dual_breath"
			"2"		"ice_path"
			"3"		"liquid_fire"
			"4"		"generic_hidden"
			"5"		"generic_hidden"
			"6"		"macropyre"
			"10"		"special_bonus_unique_imba_jakiro_1"
			"11"		"special_bonus_unique_imba_jakiro_2"
			"12"		"special_bonus_unique_imba_jakiro_3"
			"13"		"special_bonus_unique_imba_jakiro_4"
			"14"		"special_bonus_unique_imba_jakiro_5"
			"15"		"special_bonus_unique_imba_jakiro_6"
			"16"		"special_bonus_unique_imba_jakiro_7"
			"17"		"special_bonus_unique_imba_jakiro_8"
		}
		
		
	}
	"npc_dota_hero_batrider"
	{

		"1"	{
            "1"		"batrider_sticky_napalm"
		"2"		"batrider_flamebreak"
		"3"		"batrider_firefly"
		"4"		"batrider_sticky_napalm_application_damage"
		"5"		"batrider_smoldering_resin"
		"6"		"batrider_flaming_lasso"
		"10"		"special_bonus_unique_batrider_7"
		"11"		"special_bonus_unique_batrider_3"
		"12"		"special_bonus_movement_speed_20"
		"13"		"special_bonus_unique_batrider_6"
		"14"		"special_bonus_unique_batrider_1"
		"15"		"special_bonus_unique_batrider_5"
		"16"		"special_bonus_unique_batrider_4"
		"17"		"special_bonus_unique_batrider_2"
		}
"2"
		{
			"1"		"imba_batrider_sticky_napalm"
		"2"		"imba_batrider_flamebreak"
		"3"		"imba_batrider_firefly"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"imba_batrider_flaming_lasso"

		"10"		"special_bonus_imba_batrider_8"
		"11"		"special_bonus_imba_batrider_2"
		"12"		"special_bonus_imba_batrider_3"
		"13"		"special_bonus_imba_batrider_5"
		"14"		"special_bonus_imba_batrider_1"
		"15"		"special_bonus_imba_batrider_6"
		"16"		"special_bonus_imba_batrider_7"
		"17"		"special_bonus_imba_batrider_4"
		}
	
    }
	"npc_dota_hero_doom_bringer"
	{
		
		"1"	{
            "1"		"doom_bringer_devour"
		"2"		"doom_bringer_scorched_earth"
		"3"		"doom_bringer_infernal_blade"
		"4"		"doom_bringer_empty1"
		"5"		"doom_bringer_empty2"
		"6"		"doom_bringer_doom"
		"7"		"doom_bringer_lvl_pain"
		"10"		"special_bonus_unique_doom_3"
		"11"		"special_bonus_unique_doom_4"
		"12"		"special_bonus_unique_doom_6"
		"13"		"special_bonus_unique_doom_2"
		"14"		"special_bonus_unique_doom_9"
		"15"		"special_bonus_unique_doom_1"
		"16"		"special_bonus_unique_doom_10"
		"17"		"special_bonus_unique_doom_11"
		}
"2"
		{
			
		"1"	"imba_doom_bringer_devour"
		"2"	"imba_doom_bringer_scorched_earth"
		"3"	"imba_doom_bringer_infernal_blade"
		"4"	"doom_bringer_empty1"
		"5"	"doom_bringer_empty2"
		"6"	"imba_doom_bringer_doom"
		"7"	"doom_bringer_empty3"
		"8"	"doom_bringer_empty4"
		"10" "special_bonus_cast_range_125"
		"11"	"special_bonus_armor_3"
		"12" "special_bonus_imba_doom_1"
		"13" "special_bonus_imba_doom_2"
		"14" "special_bonus_imba_doom_3"
		"15" "special_bonus_imba_doom_4"
		"16" "special_bonus_imba_doom_5"
		"17" "special_bonus_cleave_175"
		}

		
	}
	"npc_dota_hero_ancient_apparition"
	{
	
		"1"	{
            "1"		"ancient_apparition_cold_feet"
		"2"		"ancient_apparition_ice_vortex"
		"3"		"ancient_apparition_chilling_touch"
		"4"		"ancient_apparition_death_rime"
		"5"		"generic_hidden"
		"6"		"ancient_apparition_ice_blast"
		"7"		"ancient_apparition_ice_blast_release"
		"10"		"special_bonus_unique_ancient_apparition_7"
		"11"		"special_bonus_unique_ancient_apparition_8"
		"12"		"special_bonus_unique_ancient_apparition_3"
		"13"		"special_bonus_unique_ancient_apparition_1"
		"14"		"special_bonus_unique_ancient_apparition_ice_vortex_duration"
		"15"		"special_bonus_unique_ancient_apparition_2"
		"16"		"special_bonus_unique_ancient_apparition_6"
		"17"		"special_bonus_unique_ancient_apparition_5"
		
		}
"2"
		{
			"1"		"cold_feet"//"ancient_apparition_cold_feet"
		"2"		"ice_vortex"//"ancient_apparition_ice_vortex"
		"3"		"chilling_touch"//"ancient_apparition_chilling_touch"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"ice_blast"//"ancient_apparition_ice_blast"
		//"7"		"generic_hidden"//"ancient_apparition_ice_blast_release"
		"10"		"special_bonus_ancient_apparition_5"
		"11"		"special_bonus_ancient_apparition_1"
		"12"		"special_bonus_ancient_apparition_3"
		"13"		"special_bonus_ancient_apparition_2"
		"14"		"special_bonus_ancient_apparition_4"
		"15"		"special_bonus_ancient_apparition_7"
		"16"		"special_bonus_ancient_apparition_8"
		"17"		"special_bonus_ancient_apparition_6"
		}
		
	}
	"npc_dota_hero_ursa"
	{
	
		"1"	{
            "1"		"ursa_earthshock"
		"2"		"ursa_overpower"
		"3"		"ursa_fury_swipes"
		"4"		"ursa_maul"
		"5"		"generic_hidden"
		"6"		"ursa_enrage"
		"10"		"special_bonus_unique_ursa_4"
		"11"		"special_bonus_mp_regen_175"
		"12"		"special_bonus_unique_ursa_earthshock_furyswipes"
		"13"		"special_bonus_unique_ursa_8"
		"14"		"special_bonus_unique_ursa_2"
		"15"		"special_bonus_unique_ursa"
		"16"		"special_bonus_unique_ursa_3"
		"17"		"special_bonus_unique_ursa_7"
		}
"2"
		{
			"1"	"imba_ursa_earthshock"
		"2"	"imba_ursa_overpower"
		"3"	"imba_ursa_fury_swipes"
		"4"	"generic_hidden"
		"5"	"generic_hidden"
		"6"	"imba_ursa_enrage"
		"10"	"special_bonus_mp_regen_175"
		"11"	"special_bonus_strength_7"
		"12"	"special_bonus_imba_ursa_1"
		"13"	"special_bonus_imba_ursa_2"
		"14"	"special_bonus_imba_ursa_3"
		"15"	"special_bonus_imba_ursa_4"
		"16"	"special_bonus_imba_ursa_5"
		"17"	"special_bonus_imba_ursa_6"
		"7"	""
		"8"	""
		"9"	""
		}
		
	}
	"npc_dota_hero_spirit_breaker"
	{
		
		"1"	{
            "1"		"spirit_breaker_charge_of_darkness"
		"2"		"spirit_breaker_bulldoze"
		"3"		"spirit_breaker_greater_bash"
		"4"		"spirit_breaker_planar_pocket"
		"5"		"spirit_breaker_herd_mentality"
		"6"		"spirit_breaker_nether_strike"
		"10"		"special_bonus_night_vision_500"
		"11"		"special_bonus_armor_4"
		"12"		"special_bonus_unique_spirit_breaker_2"
		"13"		"special_bonus_attack_damage_45"
		"14"		"special_bonus_unique_spirit_breaker_1"
		"15"		"special_bonus_unique_spirit_breaker_shield"
		"16"		"special_bonus_unique_spirit_breaker_3"
		"17"		"special_bonus_unique_spirit_breaker_4"
		}
"2"
		{
			
		"1"		"charge_of_darkness"
		"2"		"bulldoze"
		"3"		"greater_bash"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"nether_strike"
		"10"		"special_bonus_spirit_breaker_1"
		"11"		"special_bonus_spirit_breaker_2"
		"12"		"special_bonus_spirit_breaker_3"
		"13"		"special_bonus_spirit_breaker_4"
		"14"		"special_bonus_spirit_breaker_7"
		"15"		"special_bonus_spirit_breaker_6"
		"16"		"special_bonus_spirit_breaker_5"
		"17"		"special_bonus_spirit_breaker_8"
		}
	}
	"npc_dota_hero_gyrocopter"
	{
		"1"	{"1"		"gyrocopter_rocket_barrage"
		"2"		"gyrocopter_homing_missile"
		"3"		"gyrocopter_flak_cannon"
		"4"		"gyrocopter_chop_shop"
		"5"		"generic_hidden"
		"6"		"gyrocopter_call_down"
		"7"		"generic_hidden"
		"8"		"generic_hidden"
		"10"		"special_bonus_unique_gyrocopter_homing_missile_damage"
		"11"		"special_bonus_hp_175"
		"12"		"special_bonus_unique_gyrocopter_6"
		"13"		"special_bonus_unique_gyrocopter_flak_cannon_bonus_damage"
		"14"		"special_bonus_unique_gyrocopter_2"
		"15"		"special_bonus_unique_gyrocopter_3"
		"16"		"special_bonus_unique_gyrocopter_1"
		"17"		"special_bonus_unique_gyrocopter_5"
		}
"2"
		{
			"1"		"rocket_barrage"//"gyrocopter_rocket_barrage"
		"2"		"guided_missile"//"gyrocopter_homing_missile"
		"3"		"flak_cannon" //"gyrocopter_flak_cannon"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"call_down" //"gyrocopter_call_down"
		"10"		"special_bonus_gyrocopter_1"
		"11"		"special_bonus_gyrocopter_2"
		"12"		"special_bonus_gyrocopter_3"
		"13"		"special_bonus_gyrocopter_4"
		"14"		"special_bonus_gyrocopter_5"
		"15"		"special_bonus_gyrocopter_6"
		"16"		"special_bonus_gyrocopter_7"
		"17"		"special_bonus_gyrocopter_8"
		}


	
	}
	"npc_dota_hero_alchemist"
	{
		"1"	{
            "1"		"alchemist_acid_spray"
		"2"		"alchemist_unstable_concoction"
		"3"		"alchemist_corrosive_weaponry"
		"4"		"alchemist_berserk_potion"
		"5"		"alchemist_goblins_greed"
		"6"		"alchemist_chemical_rage"
		"7"		"alchemist_unstable_concoction_throw"	
		"10"		"special_bonus_unique_alchemist_5"
		"11"		"special_bonus_unique_alchemist"
		"12"		"special_bonus_unique_alchemist_3"
		"13"		"special_bonus_unique_alchemist_7"
		"14"		"special_bonus_unique_alchemist_8"
		"15"		"special_bonus_unique_alchemist_2"
		"16"		"special_bonus_unique_alchemist_6"
		"17"		"special_bonus_unique_alchemist_4"


		}
"2"
		{
			"1"		"acid_spray"
		"2"		"unstable_concoction_throw"
		"3"		"goblins_greed"
		"4"		"alchemist_berserk_potion"
		"5"		"generic_hidden"
		"6"		"chemical_rage"
		"10"		"special_bonus_alchemist_1"
		"11"		"special_bonus_alchemist_2"
		"12"		"special_bonus_alchemist_3"
		"13"		"special_bonus_alchemist_4"
		"14"		"special_bonus_alchemist_5"
		"15"		"special_bonus_attack_speed_175"
		"16"		"special_bonus_alchemist_7"
		"17"		"special_bonus_cleave_25"
		}

		
	}
	"npc_dota_hero_silencer"
	{
	
		"1"	{"1"		"silencer_curse_of_the_silent"	
		"2"		"silencer_glaives_of_wisdom"
		"3"		"silencer_last_word"
		"4"		"silencer_brain_drain"
		"5"		"generic_hidden"
		"6"		"silencer_global_silence"
		"10"		"special_bonus_unique_silencer"
		"11"		"special_bonus_attack_speed_20"
		"12"		"special_bonus_unique_silencer_7"
		"13"		"special_bonus_unique_silencer_4"
		"14"		"special_bonus_unique_silencer_glaives_bounces"
		"15"		"special_bonus_unique_silencer_arcane_curse_undispellable"
		"16"		"special_bonus_unique_silencer_3"
		"17"		"special_bonus_unique_silencer_arcane_curse_charges"

		}
"2"
		{
			"1"		"silencer_curse_of_the_silent"
		"2"		"imba_silencer_glaives_of_wisdom"
		"3"		"silencer_last_word"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"silencer_global_silence"
		"10"		"special_bonus_unique_silencer"
		"11"		"special_bonus_attack_speed_20"
		"12"		"special_bonus_unique_silencer_7"
		"13"		"special_bonus_unique_silencer_4"
		"14"		"special_bonus_unique_imba_silencer_1"
		"15"		"special_bonus_unique_silencer_arcane_curse_undispellable"
		"16"		"special_bonus_unique_imba_silencer_3"
		"17"		"special_bonus_unique_silencer_2"
		}
		
	}
	"npc_dota_hero_obsidian_destroyer"
	{
		
		"1"	{
            "1"		"obsidian_destroyer_arcane_orb"
		"2"		"obsidian_destroyer_astral_imprisonment"
		"3"		"obsidian_destroyer_equilibrium"
		"4"		"generic_hidden"
		"5"		"obsidian_destroyer_ominous_discernment"
		"6"		"obsidian_destroyer_sanity_eclipse"
		"10"		"special_bonus_hp_200"
		"11"		"special_bonus_mp_250"
		"12"		"special_bonus_unique_outworld_devourer_astral_castrange"
		"13"		"special_bonus_unique_outworld_devourer_3"
		"14"		"special_bonus_spell_lifesteal_20"
		"15"		"special_bonus_unique_outworld_devourer_4"
		"16"		"special_bonus_unique_outworld_devourer"
		"17"		"special_bonus_unique_outworld_devourer_5"
		}
"2"
		{
			"1"		"arcane_orb"
		"2"		"astral_imprisonment"
		"3"		"essence_aura"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"sanity_eclipse"
		"10"		"special_bonus_obsidian_destroyer_1"
		"11"		"special_bonus_obsidian_destroyer_2"
		"12"		"special_bonus_obsidian_destroyer_3"
		"13"		"special_bonus_obsidian_destroyer_4"
		"14"		"special_bonus_obsidian_destroyer_5"
		"15"		"special_bonus_obsidian_destroyer_6"
		"16"		"special_bonus_obsidian_destroyer_7"
		"17"		"special_bonus_obsidian_destroyer_8"
		}
		
	}
	"npc_dota_hero_lycan"
	{
		
		"1"	{"1"		"lycan_summon_wolves"
		"2"		"lycan_howl"
		"3"		"lycan_feral_impulse"
		"4"		"lycan_wolf_bite"
		"5"		"lycan_apex_predator"
		"6"		"lycan_shapeshift"
		"10"		"special_bonus_unique_lycan_howl_armor"
		"11"		"special_bonus_unique_lycan_3"
		"12"		"special_bonus_unique_lycan_7"
		"13"		"special_bonus_unique_lycan_8"
		"14"		"special_bonus_unique_lycan_1"
		"15"		"special_bonus_unique_lycan_4"
		"17"		"special_bonus_unique_lycan_2"
		"16"		"special_bonus_unique_lycan_5"
		
		}
"2"
		{
				"1"		"summon_wolves"
		"2"		"howl"
		"3"		"feral_impulse"
		"4"		"wolf_bite"
		"5"		"generic_hidden"
		"6"		"shapeshift"
		"10"		"special_bonus_lycan_1"
		"11"		"special_bonus_lycan_2"
		"12"		"special_bonus_lycan_3"
		"13"		"special_bonus_lycan_4"
		"14"		"special_bonus_lycan_5"
		"15"		"special_bonus_lycan_6"
		"17"		"special_bonus_lycan_7"
		"16"		"special_bonus_lycan_8"
		}		
	}
	"npc_dota_hero_brewmaster"
	{
		
		"1"	{"1"		"brewmaster_thunder_clap"
		"2"		"brewmaster_cinder_brew"
		"3"		"brewmaster_drunken_brawler"
		"4"		"brewmaster_primal_companion"
		"5"		"generic_hidden"
		"6"		"brewmaster_primal_split"
		"10"		"special_bonus_unique_brewmaster_2"
		"11"		"special_bonus_unique_brewmaster_7"
		"12"		"special_bonus_unique_brewmaster_5"
		"13"		"special_bonus_unique_brewmaster_8"
		"14"		"special_bonus_unique_brewmaster"
		"15"		"special_bonus_attack_speed_90"
		"16"		"special_bonus_unique_brewmaster_6"
		"17"		"special_bonus_unique_brewmaster_4"
		}
"2"
		{
			"1"	"imba_brewmaster_thunder_clap"
		"2"	"imba_brewmaster_cinder_brew"
		"3"	"imba_brewmaster_drunken_brawler"
		"4"	"imba_brewmaster_primal_resonant"
		"5"	"generic_hidden"
		"6"	"imba_brewmaster_primal_split"
		"7"  "imba_brewmaster_primal_split_switch"
		"TalentStart"	"10"
		"10"	"special_bonus_armor_7"
		"11"	"special_bonus_imba_brewmaster_1"
		"12"	"special_bonus_imba_brewmaster_3"
		"13"	"special_bonus_magic_resistance_25"
		"14"	"special_bonus_imba_brewmaster_2"
		"15"	"special_bonus_attack_speed_80"
		"16"	"special_bonus_strength_40"
		"17"	"special_bonus_imba_brewmaster_4"
		}

	
	}
	"npc_dota_hero_shadow_demon"
	{
		
		"1"	{"1"		"shadow_demon_disruption"
		"2"		"shadow_demon_disseminate"
		"3"		"shadow_demon_shadow_poison"
		"4"		"shadow_demon_shadow_poison_release"
		"5"		"shadow_demon_demonic_cleanse"
		"6"		"shadow_demon_demonic_purge"
		"7"		"shadow_demon_menace"
		"10"		"special_bonus_unique_shadow_demon_4"
		"11"		"special_bonus_strength_10"
		"12"		"special_bonus_movement_speed_25"
		"13"		"special_bonus_unique_shadow_demon_3"
		"14"		"special_bonus_unique_shadow_demon_disseminate_damage"
		"15"		"special_bonus_unique_shadow_demon_1"
		"16"		"special_bonus_unique_shadow_demon_9"
		"17"		"special_bonus_unique_shadow_demon_7"
		}
"2"
		{
			"1"					"imba_shadow_demon_disruption"
		"2"					"imba_shadow_demon_soul_catcher"
		"3"					"imba_shadow_demon_shadow_poison"
		"4"					"imba_shadow_demon_shadow_energy"
		"5"					"generic_hidden"
		"6"					"imba_shadow_demon_demonic_purge"

		"10"					"special_bonus_imba_shadow_demon_5"
		"11"					"special_bonus_imba_shadow_demon_6"
		"12"					"special_bonus_imba_shadow_demon_3"
		"13"					"special_bonus_imba_shadow_demon_1"
		"14"					"special_bonus_imba_shadow_demon_2"
		"15"					"special_bonus_imba_shadow_demon_8"
		"16"					"special_bonus_imba_shadow_demon_7"
		"17"					"special_bonus_imba_shadow_demon_4"

		}
		
	}
	"npc_dota_hero_chaos_knight"
	{
		
		"1"	{"1"		"chaos_knight_chaos_bolt"
		"2"		"chaos_knight_reality_rift"
		"3"		"chaos_knight_chaos_strike"
		"4"		"generic_hidden"
		"5"		"chaos_knight_reins_of_chaos"
		"6"		"chaos_knight_phantasm"
		"10"		"special_bonus_unique_chaos_knight_6"
		"11"		"special_bonus_unique_chaos_knight_2"
		"12"		"special_bonus_unique_chaos_knight_8"
		"13"		"special_bonus_strength_12"
		"14"		"special_bonus_unique_chaos_knight_3"
		"15"		"special_bonus_unique_chaos_knight"
		"16"		"special_bonus_unique_chaos_knight_5"
		"17"		"special_bonus_unique_chaos_knight_4"

		}
"2"
		{
			"1"	"imba_chaos_knight_chaos_bolt"
		"2"	"imba_chaos_knight_reality_rift"
		"3"	"imba_chaos_knight_chaos_strike"
		"4"	"generic_hidden"
		"5"	"generic_hidden"
		"6"	"imba_chaos_knight_chaos"
		"10"	"special_bonus_custom_value_all15"
		"11"	"special_bonus_custom_value_msp60"
		"12"	"special_bonus_custom_value_asp75"
		"13"	"special_bonus_custom_value_castrange200"
		"14"	"special_bonus_imba_chaos_knight_4"
		"15"	"special_bonus_imba_chaos_knight_3"
		"16"	"special_bonus_imba_chaos_knight_2"
		"17"	"special_bonus_custom_value_cd20"
		"7"	""
		"8"	""
		"9"	""
		}

		
	}
	"npc_dota_hero_treant"
	{

		"1"	{
            "1"		"treant_natures_grasp"
		"2"		"treant_leech_seed"
		"3"		"treant_living_armor"
		"4"		"treant_eyes_in_the_forest"
		"5"		"treant_natures_guise"
		"6"		"treant_overgrowth"
		"7"		"treant_innate_attack_damage"
		"10"		"special_bonus_unique_treant_8"
		"11"		"special_bonus_unique_treant_12"
		"12"		"special_bonus_unique_treant_3"
		"13"		"special_bonus_unique_treant_9"
		"14"		"special_bonus_unique_treant_13"
		"15"		"special_bonus_unique_treant_2"
		"16"		"special_bonus_unique_treant_14"
		"17"		"special_bonus_unique_treant_7"
		}
"2"
		{
			"1"		"imba_treant_natures_grasp"
		"2"		"imba_treant_leech_seed"
		"3"		"imba_treant_living_armor"
		"4"		"imba_treant_eyes_in_the_forest"
		"5"		"imba_treant_natures_guise"
		"6"		"imba_treant_overgrowth"
		"7"		"treant_eyes_in_the_forest"
		"10"		"special_bonus_imba_treant_1"
		"11"		"special_bonus_imba_treant_2"
		"12"		"special_bonus_imba_treant_3"
		"13"		"special_bonus_imba_treant_4"
		"14"		"special_bonus_imba_treant_5"
		"15"		"special_bonus_imba_treant_6"
		"16"		"special_bonus_imba_treant_7"
		"17"		"special_bonus_imba_treant_8"
		}

	
	}
	"npc_dota_hero_ogre_magi"
	{
	
		"1"	{
            "1"		"ogre_magi_fireblast"
		"2"		"ogre_magi_ignite"
		"3"		"ogre_magi_bloodlust"
		"4"		"ogre_magi_unrefined_fireblast"
		"5"		"ogre_magi_smash"
		"6"		"ogre_magi_dumb_luck"
		"7"		"ogre_magi_multicast"
		"10"		"special_bonus_unique_ogre_magi_4"
		"11"		"special_bonus_unique_ogre_magi_5"
		"12"		"special_bonus_attack_damage_80"
		"13"		"special_bonus_unique_ogre_magi_dumb_luck_mana"
		"14"		"special_bonus_strength_30"
		"15"		"special_bonus_unique_ogre_magi"
		"16"		"special_bonus_unique_ogre_magi_3"
		"17"		"special_bonus_unique_ogre_magi_2"

		}
"2"
		{
			"1"	"imba_ogre_magi_fireblast_ignite"
		"2"	"imba_ogre_magi_focus"
		"3"	"imba_ogre_magi_Bloodlust"
		"4"	"generic_hidden"
		"5"	"generic_hidden"
		"6"	"imba_ogre_magi_multicast"
		"7"	"ogre_magi_dumb_luck"
        //"14" "special_bonus_imba_ogre_magi_2"
        //"12"	"special_bonus_imba_ogre_magi_8"
		
		"10"	"special_bonus_imba_ogre_magi_7"
		"11"	"special_bonus_imba_ogre_magi_5"
		"12" "special_bonus_attack_damage_100"
		"13" "special_bonus_imba_ogre_magi_3"
		"14"	"special_bonus_strength_40"
		"15"	"special_bonus_imba_ogre_magi_6"
		"16"	"special_bonus_imba_ogre_magi_4"
		"17"	"special_bonus_imba_ogre_magi_1"
		}
		
	
	}
	"npc_dota_hero_undying"
	{
		
		"1"	{"1"		"undying_decay"
		"2"		"undying_soul_rip"
		"3"		"undying_tombstone"
		"4"		"undying_ceaseless_dirge"
		"5"		"generic_hidden"
		"6"		"undying_flesh_golem"
		"10"		"special_bonus_unique_undying_8"
		"11"		"special_bonus_unique_undying_7"
		"12"		"special_bonus_unique_undying"
		"13"		"special_bonus_unique_undying_6"
		"14"		"special_bonus_unique_undying_3"
		"15"		"special_bonus_unique_undying_2"
		"16"		"special_bonus_unique_undying_4"
		"17"		"special_bonus_unique_undying_5"
		}
"2"
		{
			"1"		"decay"
		"2"		"soul_rip"
		"3"		"tombstone"
		"4"		"plague_world"
		"5"		"zombie_virus"
		"6"		"flesh_golem"
		"10"		"special_bonus_undying_1"
		"11"		"special_bonus_undying_2"
		"12"		"special_bonus_undying_3"
		"13"		"special_bonus_undying_4"
		"14"		"special_bonus_undying_5"
		"15"		"special_bonus_undying_6"
		"16"		"special_bonus_reincarnation_300"
		"17"		"special_bonus_undying_7"

		}
		
	}
	"npc_dota_hero_disruptor"
	{
		
		"GibType"		"default"
		"1"	{"1"		"disruptor_thunder_strike"
		"2"		"disruptor_glimpse"
		"3"		"disruptor_kinetic_field"
		"4"		"disruptor_electromagnetic_repulsion"
		"5"		"generic_hidden"
		"6"		"disruptor_static_storm"
		"10"		"special_bonus_unique_disruptor_2"
		"11"		"special_bonus_unique_disruptor_consecutive_strike_damage"
		"12"		"special_bonus_unique_disruptor_9"
		"13"		"special_bonus_unique_disruptor_7"
		"14"		"special_bonus_unique_disruptor_5"
		"15"		"special_bonus_unique_disruptor"
		"16"		"special_bonus_unique_disruptor_4"
		"17"		"special_bonus_unique_disruptor_8"
		
		}
"2"
		{
			"1"	"imba_disruptor_thunder_strike"
		"2"	"imba_disruptor_glimpse"
		"3"	"imba_disruptor_kinetic_field"
		"4"	"generic_hidden"
		"5"	"generic_hidden"
		"6"	"imba_disruptor_static_storm"
		"10"	"special_bonus_hp_200"
		"11"	"special_bonus_imba_disruptor_1"
		"12"	"special_bonus_cast_range_150"
		"13"	"special_bonus_imba_disruptor_4"
		"14"	"special_bonus_imba_disruptor_2"
		"15"	"special_bonus_imba_disruptor_3"
		"16"	"special_bonus_cooldown_reduction_10"
		"17"	"special_bonus_imba_disruptor_6"
		"7"	""
		"8"	""
		"9"	""
		}
		
		
	}
	"npc_dota_hero_nyx_assassin"
	{
		
		"1"	{
            "1"		"nyx_assassin_impale"
		"2"		"nyx_assassin_jolt"
		"3"		"nyx_assassin_spiked_carapace"
		"4"		"nyx_assassin_burrow"
		"5"		"nyx_assassin_nyxth_sense"
		"6"		"nyx_assassin_vendetta"
		"7"		"nyx_assassin_unburrow"
		"10"		"special_bonus_unique_nyx_vendetta_damage"
		"11"		"special_bonus_unique_nyx_4"
		"12"		"special_bonus_unique_nyx_carapace_reflect_duration"
		"13"		"special_bonus_unique_nyx_jolt_cooldown"
		"14"		"special_bonus_unique_nyx_6"
		"15"		"special_bonus_unique_nyx_2"
		"16"		"special_bonus_unique_nyx"
		"17"		"special_bonus_unique_nyx_vendetta_cd_manacost"
		
		
		}
"2"
		{
		"1"		"imba_nyx_assassin_impale"
		"2"		"nyx_assassin_jolt"		//"imba_nyx_assassin_mana_burn"
		"3"		"imba_nyx_assassin_spiked_carapace"
		"4"		"imba_nyx_assassin_burrow"
		"5"		"generic_hidden"
		"6"		"imba_nyx_assassin_vendetta"
		"7"		"imba_nyx_assassin_unburrow"
		"10"		"special_bonus_spell_amplify_8"
		"11"		"special_bonus_imba_nyx_assassin_1"
		"12"		"special_bonus_unique_nyx_5"
		"13"		"special_bonus_movement_speed_20"
		"14"		"special_bonus_imba_nyx_assassin_2"
		"15"		"special_bonus_imba_nyx_assassin_3"
		"16"		"special_bonus_agility_80"
		"17"		"special_bonus_imba_nyx_assassin_4"
		}
		
		
	}
	"npc_dota_hero_naga_siren"
	{
	
		"1"	{"1"		"naga_siren_mirror_image"
		"2"		"naga_siren_ensnare"
		"3"		"generic_hidden"
		"4"		"naga_siren_reel_in"
		"5"		"naga_siren_eelskin"
		"6"		"naga_siren_song_of_the_siren"
		"7"		"naga_siren_song_of_the_siren_cancel"
		"10"		"special_bonus_unique_naga_siren_net_cooldown"
		"11"		"special_bonus_unique_naga_siren_2"
		"12"		"special_bonus_unique_naga_siren_4"
		"13"		"special_bonus_unique_naga_siren_3"
		"14"		"special_bonus_unique_naga_siren_5"
		"15"		"special_bonus_unique_naga_siren"
		"16"		"special_bonus_unique_naga_siren_6"
		"17"		"special_bonus_unique_naga_siren_net_breaks"
		}
"2"
		{
				"1"		"ensnare"//"naga_siren_mirror_image"
		"2"		"rip_tide"//"naga_siren_ensnare"
		"3"		"song_of_the_siren"//"naga_siren_rip_tide"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"mirror_image"//"naga_siren_song_of_the_siren"
		//"7"		//"naga_siren_song_of_the_siren_cancel"
		//"10"		"special_bonus_custom_value_all15"
		"10"     "special_bonus_naga_siren_1"
		//"11"     "special_bonus_naga_siren_2"
		"11"		"special_bonus_custom_value_msp60"
		"12"		"special_bonus_naga_siren_3"
		"13"		"special_bonus_agility_40"
		//"13"		"special_bonus_naga_siren_4"
		//"14"		"special_bonus_custom_value_ap15"
		"14"		"special_bonus_naga_siren_5"
		//"15"		"special_bonus_custom_value_cd10"
		"15"		"special_bonus_naga_siren_6"
		"16"     "special_bonus_naga_siren_7"
		//"16"	"special_bonus_custom_value_asp200"
		"17"		"special_bonus_naga_siren_8"
		//"17"		"special_bonus_custom_value_att150"

		}
		
	}
	"npc_dota_hero_keeper_of_the_light"
	{
		
		"1"	{"1"		"keeper_of_the_light_illuminate"
		"2"		"keeper_of_the_light_blinding_light"
		"3"		"keeper_of_the_light_chakra_magic"
		"4"		"generic_hidden"
		"5"		"keeper_of_the_light_will_o_wisp"
		"6"		"keeper_of_the_light_spirit_form"
		"7"		"keeper_of_the_light_illuminate_end"
		"8"		"keeper_of_the_light_mana_magnifier"
		"9"		"generic_hidden"
		"10"		"generic_hidden"
		"11"		"special_bonus_unique_keeper_of_the_light_8"
		"12"		"special_bonus_unique_keeper_of_the_light_illuminate_cooldown"
		"13"		"special_bonus_unique_keeper_of_the_light_7"
		"14"		"special_bonus_unique_keeper_of_the_light_5"
		"15"		"special_bonus_unique_keeper_of_the_light_11"
		"16"		"special_bonus_unique_keeper_of_the_light_2"
		"17"		"special_bonus_unique_keeper_of_the_light_14"
		"18"		"special_bonus_unique_keeper_of_the_light"
		
		}
"2"
		{
			"1"		"imba_light_illuminate"
		"2"		"imba_light_radiant_bind"
		"3"		"imba_light_blinding_light"
		"4"		"imba_light_spirit_form"
		"5"		"generic_hidden"
		"6"		"imba_light_will_o_wisp"

		"11"		"special_bonus_imba_keeper_of_the_light_1"
		"12"		"special_bonus_imba_keeper_of_the_light_2"
		"13"		"special_bonus_imba_keeper_of_the_light_3"
		"14"		"special_bonus_imba_keeper_of_the_light_4"
		"15"		"special_bonus_imba_keeper_of_the_light_5"
		"16"		"special_bonus_imba_keeper_of_the_light_6"
		"17"		"special_bonus_imba_keeper_of_the_light_7"
		"18"		"special_bonus_imba_keeper_of_the_light_8"
		}		
		
	}
	"npc_dota_hero_wisp"
	{
		
		"1"	{"1"		"wisp_tether"
		"2"		"wisp_spirits"		
		"3"		"wisp_overcharge"
		"4"		"wisp_spirits_in"
		"5"		"wisp_spirits_out"
		"6"		"wisp_relocate"
		"7"		"wisp_tether_break"
		"8"		"wisp_sight_seer"
		"10"		"special_bonus_unique_wisp_11"
		"11"		"special_bonus_unique_wisp_8"
		"12"		"special_bonus_unique_wisp_3"
		"13"		"special_bonus_unique_wisp"
		"14"		"special_bonus_unique_wisp_10"
		"15"		"special_bonus_unique_wisp_6"
		"16"		"special_bonus_unique_wisp_9"
		"17"		"special_bonus_unique_wisp_4"
		
		}
"2"
		{
			"1"		"imba_wisp_tether"
		"2"		"imba_wisp_spirits"
		"3"		"imba_wisp_overcharge"		
		"4"		"imba_wisp_element_territory"
		"5"		"generic_hidden"
		"6"		"imba_wisp_relocate"
		"7"		"imba_wisp_tether_break"
		
		"10"		"special_bonus_imba_wisp_1"
		"11"		"special_bonus_imba_wisp_2"
		"12"		"special_bonus_imba_wisp_3"
		"13"		"special_bonus_imba_wisp_7"
		"14"		"special_bonus_imba_wisp_5"
		"15"		"special_bonus_imba_wisp_8"
		"16"		"special_bonus_imba_wisp_6"
		"17"		"special_bonus_imba_wisp_4"
		}
		
		
	}
	"npc_dota_hero_visage"
	{
	
		"1"	{"1"		"visage_grave_chill"
		"2"		"visage_soul_assumption"
		"3"		"visage_gravekeepers_cloak"
		"4"		"visage_stone_form_self_cast"
		"5"		"visage_silent_as_the_grave"
		"6"		"visage_summon_familiars"
		"7"		"visage_summon_familiars_stone_form"
		"DraftIgnoreCount" "7"
		"10"		"special_bonus_unique_visage_8"
		"11"		"special_bonus_unique_visage_7"
		"12"		"special_bonus_unique_visage_grave_chill_duration"
		"13"		"special_bonus_unique_visage_3"
		"14"		"special_bonus_unique_visage_4"
		"15"		"special_bonus_unique_visage_1"
		"16"		"special_bonus_unique_visage_5"
		"17"		"special_bonus_unique_visage_6"
		}
"2"
		{
				"1"	"imba_visage_grave_chill"
		"2"	"imba_visage_soul_assumption"
		"3"	"imba_visage_gravekeepers_cloak"
		"4"	"imba_visage_stone_form_self_cast"
		"5"	"imba_visage_silent_as_the_grave"
		"6"	"imba_visage_summon_familiars"
		"10"	"special_bonus_exp_boost_15"
		"11"	"special_bonus_attack_damage_30"
		"12"	"special_bonus_cast_range_200"
		"13"	"special_bonus_imba_visage_2"
		"14"	"special_bonus_imba_visage_3"
		"15"	"special_bonus_imba_visage_5"
		"16"	"special_bonus_imba_visage_1"
		"17"	"special_bonus_imba_visage_4"
		}
	}
	"npc_dota_hero_slark"
	{
	
		"1"	{"1"		"slark_dark_pact"
		"2"		"slark_pounce"
		"3"		"slark_essence_shift"
		"4"		"slark_depth_shroud"
		"5"		"slark_barracuda"
		"6"		"slark_shadow_dance"
		"10"		"special_bonus_unique_slark_6"
		"11"		"special_bonus_unique_slark"
		"12"		"special_bonus_unique_slark_2"
		"13"		"special_bonus_unique_slark_8"
		"14"		"special_bonus_unique_slark_5"
		"15"		"special_bonus_unique_slark_7"
		"16"		"special_bonus_unique_slark_3"
		"17"		"special_bonus_unique_slark_4"
		}
"2"
		{
			"1"	"imba_slark_dark_pact"
		"2"	"imba_slark_pounce"
		"3"	"imba_slark_essence_shift"
		"4"	"imba_slark_fish_bait"
		"5"	"generic_hidden"
		"6"	"imba_slark_shadow_dance"
		"10"	"special_bonus_strength_5"
		"11"	"special_bonus_agility_8"
		"12"	"special_bonus_attack_speed_30"
		"13"	"special_bonus_lifesteal_20"
		"14"	"special_bonus_imba_slark_2"
		"15"	"special_bonus_imba_slark_1"
		"16"	"special_bonus_attack_damage_100"
		"17"	"special_bonus_hp_500"
		"7"	""
		"8"	""
		"9"	""
		}

		
	}
	"npc_dota_hero_medusa"
	{
		"1"	{"1"		"medusa_split_shot"
		"2"		"medusa_mystic_snake"
		"3"		"medusa_mana_shield"
		"4"		"medusa_cold_blooded"
		"5"		"generic_hidden"
		"6"		"medusa_stone_gaze"
		"10"		"special_bonus_unique_medusa_snake_damage"
		"11"		"special_bonus_unique_medusa_8"
		"12"		"special_bonus_unique_medusa_2"
		"13"		"special_bonus_unique_medusa_5"
		"14"		"special_bonus_unique_medusa_3"
		"15"		"special_bonus_unique_medusa"
		"16"		"special_bonus_unique_medusa_6"
		"17"		"special_bonus_unique_medusa_4"
		}
"2"
		{
			"1"		"medusa_split_shot"
		"2"		"mystic_snake"
		"3"		"mana_shield"
		"4"		"medusa_cold_blooded"
		"5"		"medusa_mystic_snake"
		"6"		"stone_gaze"
		"10"		"special_bonus_mp_300"
		"11"		"special_bonus_medusa_2"
		"12"		"special_bonus_medusa_3"
		"13"		"special_bonus_medusa_4"
		"14"		"special_bonus_medusa_5"
		"15"		"special_bonus_custom_value_all25"
		"16"		"special_bonus_unique_medusa_4"
		"17"		"special_bonus_medusa_1"
		}
		
	}
	"npc_dota_hero_centaur"
	{
		
		"1"	{"1"		"centaur_hoof_stomp"
		"2"		"centaur_double_edge"
		"3"		"centaur_return"
		"4"		"centaur_mount"
		"5"		"centaur_work_horse"
		"6"		"centaur_stampede"
		"7"		"centaur_rawhide"
		"10"		"special_bonus_hp_regen_4"
		"11"		"special_bonus_movement_speed_20"
		"12"		"special_bonus_strength_15"
		"13"		"special_bonus_unique_centaur_4"
		"14"		"special_bonus_unique_centaur_3"
		"15"		"special_bonus_unique_centaur_5"
		"16"		"special_bonus_unique_centaur_1"
		"17"		"special_bonus_unique_centaur_2"
		
		}
"2"
		{
				"1"		"hoof_stomp"//"centaur_hoof_stomp"
		"2"		"double_edge"			//"centaur_double_edge"
		"3"		"c_return"//"centaur_return"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"stampede"	//"centaur_stampede"
		"10"		"special_bonus_centaur_1"
		"11"		"special_bonus_centaur_2"
		"12"		"special_bonus_centaur_3"
		"13"		"special_bonus_centaur_4"
		"14"		"special_bonus_centaur_5"
		"15"		"special_bonus_centaur_6"
		"16"		"special_bonus_centaur_7"
		"17"		"special_bonus_centaur_8"


		}
	
	}
	"npc_dota_hero_magnataur"
	{
	
		"1"	{"1"		"magnataur_shockwave"
		"2"		"magnataur_empower"
		"3"		"magnataur_skewer"
		"4"		"magnataur_horn_toss"
		"5"		"magnataur_solid_core"
		"6"		"magnataur_reverse_polarity"
		"10"		"special_bonus_unique_magnus_4"
		"11"		"special_bonus_unique_magnus_6"
		"12"		"special_bonus_unique_magnus_reverse_polarity_stats"
		"13"		"special_bonus_unique_magnus_7"
		"14"		"special_bonus_unique_magnus"
		"15"		"special_bonus_unique_magnus_3"
		"16"		"special_bonus_unique_magnus_2"
		"17"		"special_bonus_unique_magnus_5"
		}
"2"
		{
		"1"		"shockwave"
		"2"		"empower"
		"3"		"skewer"
		"4"		"magnataur_horn_toss"
		"5"		"generic_hidden"
		"6"		"reverse_polarity"
		"10"		"special_bonus_magnataur_1"
		"11"		"special_bonus_magnataur_2"
		"12"		"special_bonus_magnataur_3"
		"13"		"special_bonus_magnataur_4"
		"14"		"special_bonus_magnataur_5"
		"15"		"special_bonus_magnataur_6"
		"16"		"special_bonus_magnataur_7"
		"17"		"special_bonus_magnataur_8"
		}

	
	}
	"npc_dota_hero_shredder"
	{
		
		"1"	{"1"		"shredder_whirling_death"
		"2"		"shredder_timber_chain"
		"3"		"shredder_reactive_armor"
		"4"		"generic_hidden"
		"5"		"shredder_flamethrower"
		"6"		"shredder_chakram"
		"7"		"shredder_return_chakram"
		"8"		"shredder_return_chakram_2"
		"9"		"shredder_exposure_therapy"
		"10"		"special_bonus_unique_timbersaw_reactive_armor_regen_per_stack"
		"11"		"special_bonus_mp_regen_150"
		"12"		"special_bonus_unique_timbersaw_5"
		"13"		"special_bonus_unique_timbersaw_2"
		"14"		"special_bonus_magic_resistance_20"
		"15"		"special_bonus_unique_timbersaw_4"
		"16"		"special_bonus_unique_timbersaw"
		"17"		"special_bonus_unique_timbersaw_3"

		}
"2"
		{
			"1"	"imba_shredder_whirling_death"
		"2"	"imba_shredder_timber_chain"
		"3"	"imba_shredder_reactive_armor"
		"4"	"imba_shredder_chakram_2"
		"5"	"imba_shredder_timber_chain_destroy"
		"6"	"imba_shredder_chakram"

		"10"	"special_bonus_shredder_6"
		"11"	"special_bonus_shredder_8"
		"12"	"special_bonus_shredder_3"
		"13"	"special_bonus_shredder_4"
		"14"	"special_bonus_shredder_2"
		"15"	"special_bonus_shredder_5"
		"16"	"special_bonus_shredder_7"
		"17"	"special_bonus_shredder_1"

		}
		
	}
	"npc_dota_hero_bristleback"
	{
		
		"1"	{
			"1"		"bristleback_viscous_nasal_goo"
		"2"		"bristleback_quill_spray"
		"3"		"bristleback_bristleback"
		"4"		"bristleback_hairball"
		"5"		"generic_hidden"
		"6"		"bristleback_warpath"
		"10"		"special_bonus_attack_speed_25"
		"11"		"special_bonus_mp_regen_150"
		"12"		"special_bonus_unique_bristleback_5"
		"13"		"special_bonus_unique_bristleback_6"
		"14"		"special_bonus_hp_regen_25"
		"15"		"special_bonus_unique_bristleback_2"
		"16"		"special_bonus_spell_lifesteal_50"
		"17"		"special_bonus_unique_bristleback_3"
		
		}
        "2"
		{
		
		"1"		"imba_bristleback_viscous_nasal_goo"
		"2"		"imba_bristleback_quill_spray"
		"3"		"imba_bristleback_bristleback"
		"4"		"imba_bristleback_hairball"
		"5"		"generic_hidden"
		"6"		"imba_bristleback_warpath"
		"10"		"special_bonus_movement_speed_20"
		"11"		"special_bonus_imba_bristleback_3"
		"12"		"special_bonus_magic_resistance_25"
		"13"		"special_bonus_imba_bristleback_2"
		"14"		"special_bonus_imba_bristleback_4"
		"15"		"special_bonus_imba_bristleback_5"
		"16"		"special_bonus_imba_bristleback_6"
		"17"		"special_bonus_spell_lifesteal_30"
		
	
	}
    }
	"npc_dota_hero_skywrath_mage"
	{
		
		"1"	{"1"		"skywrath_mage_arcane_bolt"
		"2"		"skywrath_mage_concussive_shot"
		"3"		"skywrath_mage_ancient_seal"
		"4"		"generic_hidden"	// RESERVED FOR FACET 
		"5"		"skywrath_mage_ruin_and_restoration"
		"6"		"skywrath_mage_mystic_flare"
		"10"		"special_bonus_mp_regen_150"
		"11"		"special_bonus_unique_skywrath_2"
		"12"		"special_bonus_unique_skywrath"
		"13"		"special_bonus_unique_skywrath_arcane_bolt_lifesteal"
		"14"		"special_bonus_unique_skywrath_4"
		"15"		"special_bonus_unique_skywrath_3"
		"16"		"special_bonus_unique_skywrath_6"
		"17"		"special_bonus_unique_skywrath_5"

		}
"2"
		{
			"1"	"oldsky_abolt"
		"2"	"oldsky_cshot"
		"3"	"oldsky_aseal"
		"4"	"skywrath_mage_shield_of_the_scion"
		"5"	"generic_hidden"
		"6"	"oldsky_mflare"
		"10""special_bonus_custom_value_all15"                    //10r
		"11"	"special_bonus_custom_value_msp30"            //10l
		"12"	"special_bonus_oldsky_15r"          //15r减上古封印cd
		"13"	"special_bonus_oldsky_15l"           //15l加上古封印减魔抗
		"14"	"special_bonus_custom_value_ap20"               //20r
		"15"	"special_bonus_custom_value_castrange150"       //20l
		"16"	"special_bonus_oldsky_25r"          //25r加1个C
		"17"	"special_bonus_oldsky_25l"        //25l范围震荡光蛋
		"7"	""
		"8"	""
		"9"	""
		}

	}
	"npc_dota_hero_elder_titan"
	{
		
		"HeroSelectSoundEffect"		"Hero_ElderTitan.Pick"
		"GibType"		"default"
		"1"	{"1"		"elder_titan_echo_stomp"
		"2"		"elder_titan_ancestral_spirit"
		"3"		"elder_titan_natural_order"
		"4"		"elder_titan_move_spirit"
		"5"		"generic_hidden"
		"6"		"elder_titan_earth_splitter"
		"7"		"elder_titan_return_spirit"
		"10"		"special_bonus_unique_elder_titan_bonus_spirit_speed"
		"11"		"special_bonus_attack_speed_25"
		"12"		"special_bonus_unique_elder_titan_2"
		"13"		"special_bonus_unique_elder_titan"
		"14"		"special_bonus_cleave_100"
		"15"		"special_bonus_unique_elder_titan_5"
		"16"		"special_bonus_unique_elder_titan_3"
		"17"		"special_bonus_unique_elder_titan_4"

		}
"2"
		{
			"1"		"echo_stomp"      //"elder_titan_echo_stomp"
		"2"		"ancestral_spirit" //"elder_titan_ancestral_spirit"
		"3"		"natural_order" //"elder_titan_natural_order"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"earth_splitter"	//"elder_titan_earth_splitter"
		"7"		"return_spirit" //"elder_titan_return_spirit"
		"10"		"special_bonus_elder_titan_1"//"special_bonus_unique_imba_elder_titan_1"
		"11"		"special_bonus_elder_titan_2"
		"12"		"special_bonus_elder_titan_3"
		"13"		"special_bonus_elder_titan_4"
		"14"		"special_bonus_elder_titan_5"
		"15"		"special_bonus_elder_titan_6"
		"16"		"special_bonus_elder_titan_7"
		"17"		"special_bonus_cleave_100"
		}
		
	}
	"npc_dota_hero_legion_commander"
	{
		
		"GibType"		"default"
		"1"	{"1"		"legion_commander_overwhelming_odds"
		"2"		"legion_commander_press_the_attack"
		"3"		"legion_commander_moment_of_courage"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"legion_commander_duel"
		"10"		"special_bonus_unique_legion_commander_9"
		"11"		"special_bonus_unique_legion_commander_pta_movespeed"
		"12"		"special_bonus_unique_legion_commander_6"
		"13"		"special_bonus_unique_legion_commander_4"
		"14"		"special_bonus_unique_legion_commander_5"
		"15"		"special_bonus_unique_legion_commander_3"
		"16"		"special_bonus_unique_legion_commander_7"
		"17"		"special_bonus_unique_legion_commander_8"
		}
"2"
		{
			"1"	"imba_legion_commander_overwhelming_odds"
		"2"	"imba_legion_commander_press_the_attack"
		"3"	"imba_legion_commander_moment_of_courage"
		"4"	"generic_hidden"
		"5"	"generic_hidden"
		"6"	"imba_legion_commander_duel"
		"10"	"special_bonus_strength_15"
		"11"	"special_bonus_exp_boost_15"
		"12"	"special_bonus_attack_speed_80"
		"13"	"special_bonus_imba_legion_commander_5"
		"14"	"special_bonus_movement_speed_100"
		"15"	"special_bonus_imba_legion_commander_2"
		"16"	"special_bonus_imba_legion_commander_3"
		"17"	"special_bonus_imba_legion_commander_4"
		"7"	""
		"8"	""
		"9"	""
		}
	
	}
	"npc_dota_hero_ember_spirit"
	{
		"1"	{"1"		"ember_spirit_searing_chains"
		"2"		"ember_spirit_sleight_of_fist"
		"3"		"ember_spirit_flame_guard"
		"4"		"ember_spirit_activate_fire_remnant"
		"5"		"generic_hidden"
		"6"		"ember_spirit_fire_remnant"
		"10"		"special_bonus_attack_damage_12"
		"11"		"special_bonus_unique_ember_spirit_1"
		"12"		"special_bonus_unique_ember_spirit_3"
		"13"		"special_bonus_unique_ember_spirit_2"
		"14"		"special_bonus_unique_ember_spirit_chains_dps"
		"15"		"special_bonus_unique_ember_spirit_6"
		"16"		"special_bonus_unique_ember_spirit_4"
		"17"		"special_bonus_unique_ember_spirit_5"
		}
"2"
		{
			"1"		"searing_chains"
		"2"		"sleight_of_fist"
		"3"		"flame_guard"
		"4"		"activate_fire_remnant"
		"5"		"generic_hidden"
		"6"		"fire_remnant"
		"10"		"special_bonus_ember_spirit_7"
		"11"		"special_bonus_ember_spirit_1"
		"12"		"special_bonus_ember_spirit_5"
		"13"		"special_bonus_ember_spirit_4"
		"14"		"special_bonus_ember_spirit_3"
		"15"		"special_bonus_ember_spirit_6"
		"16"		"special_bonus_ember_spirit_2"
		"17"		"special_bonus_custom_value_mgr30"
		}
		
	}
	"npc_dota_hero_earth_spirit"
	{
		"1"	{"1"		"earth_spirit_boulder_smash"
		"2"		"earth_spirit_rolling_boulder"
		"3"		"earth_spirit_geomagnetic_grip"
		"4"		"earth_spirit_stone_caller"
		"5"		"earth_spirit_petrify"
		"6"		"earth_spirit_magnetize"
		"10"		"special_bonus_unique_earth_spirit_4"
		"11"		"special_bonus_spell_amplify_10"
		"12"		"special_bonus_unique_earth_spirit_8"
		"13"		"special_bonus_unique_earth_spirit"
		"14"		"special_bonus_unique_earth_spirit_6"
		"15"		"special_bonus_unique_earth_spirit_5"
		"16"		"special_bonus_unique_earth_spirit_2"
		"17"		"special_bonus_unique_earth_spirit_3"
		}
"2"
		{
			"1"		"earth_spirit_boulder_smash"
		"2"		"earth_spirit_rolling_boulder"
		"3"		"earth_spirit_geomagnetic_grip"
		"4"		"earth_spirit_stone_caller"
		"5"		"earth_spirit_petrify"
		"6"		"earth_spirit_magnetize"
		"10"		"special_bonus_unique_earth_spirit_2"
		"11"		"special_bonus_unique_earth_spirit_3"
		"12"		"special_bonus_armor_8"
		"13"		"special_bonus_unique_earth_spirit"
		"14"		"special_bonus_spell_amplify_18"
		"15"		"special_bonus_unique_earth_spirit_5"
		"16"		"special_bonus_unique_earth_spirit_4"
		"17"		"special_bonus_attack_damage_60"
		}
		
	}
	"npc_dota_hero_terrorblade"
	{
	
		"1"	{"1"		"terrorblade_reflection"
		"2"		"terrorblade_conjure_image"
		"3"		"terrorblade_metamorphosis"
		"4"		"terrorblade_demon_zeal"
		"5"		"terrorblade_terror_wave"
		"6"		"terrorblade_sunder"
		"7"		"terrorblade_dark_unity"
		"10"		"special_bonus_unique_terrorblade_2"
		"11"		"special_bonus_unique_terrorblade_4"
		"12"		"special_bonus_unique_terrorblade_metamorphosis_cooldown"
		"13"		"special_bonus_unique_terrorblade_6"
		"14"		"special_bonus_all_stats_10"
		"15"		"special_bonus_unique_terrorblade_5"
		"16"		"special_bonus_unique_terrorblade"
		"17"		"special_bonus_unique_terrorblade_3"
		}
"2"
		{
		"1"		"imba_terrorblade_reflection"
		"2"		"terrorblade_conjure_image"
		"3"		"imba_terrorblade_metamorphosis"
		"4"		"imba_terrorblade_demonic_power"
		"5"		"generic_hidden"
		"6"		"imba_terrorblade_sunder"
		
		"10"		"special_bonus_imba_terrorblade_4"
		"11"		"special_bonus_imba_terrorblade_6"
		"12"		"special_bonus_imba_terrorblade_5"
		"13"		"special_bonus_imba_terrorblade_1"
		"14"		"special_bonus_imba_terrorblade_2"
		"15"		"special_bonus_imba_terrorblade_7"
		"16"		"special_bonus_imba_terrorblade_8"
		"17"		"special_bonus_imba_terrorblade_3"

		}
		
	}
	"npc_dota_hero_phoenix"
	{
		"1"	{
            "1"		"phoenix_icarus_dive"
		"2"		"phoenix_fire_spirits"
		"3"		"phoenix_sun_ray"
		"4"		"phoenix_sun_ray_toggle_move"
		"5"		"phoenix_blinding_sun"
		"6"		"phoenix_supernova"
		"7"		"phoenix_launch_fire_spirit"
		"8"		"phoenix_icarus_dive_stop"
		"9"		"phoenix_sun_ray_stop"
		"10"		"special_bonus_unique_phoenix_6"
		"11"		"special_bonus_unique_phoenix_dive_damage"
		"12"		"special_bonus_unique_phoenix_3"
		"13"		"special_bonus_hp_regen_20"
		"14"		"special_bonus_unique_phoenix_5"
		"15"		"special_bonus_unique_phoenix_2"
		"16"		"special_bonus_unique_phoenix_1"
		"17"		"special_bonus_unique_phoenix_4"
		
		}
"2"
		{
			"1"		"icarus_dive"
		"2"		"fire_spirits"
		"3"		"sun_ray"
		"4"		"sun_ray_toggle_move"
		"5"		"sun_ray_stop"
		"6"		"supernova"
		"7"		"launch_fire_spirit"
		"10"		"special_bonus_phoenix_1"
		"11"		"special_bonus_phoenix_2"
		"12"		"special_bonus_phoenix_3"
		"13"		"special_bonus_phoenix_4"
		"14"		"special_bonus_phoenix_5"
		"15"		"special_bonus_phoenix_6"
		"16"		"special_bonus_phoenix_7"
		"17"		"special_bonus_phoenix_8"
		}
		
		
	}
	"npc_dota_hero_oracle"
	{
	
		"1"	{"1"		"oracle_fortunes_end"
		"2"		"oracle_fates_edict"
		"3"		"oracle_purifying_flames"
		"4"		"oracle_rain_of_destiny"
		"5"		"oracle_prognosticate"
		"6"		"oracle_false_promise"
		"10"		"special_bonus_unique_oracle_2"
		"11"		"special_bonus_unique_oracle_9"
		"12"		"special_bonus_unique_oracle_damage_per_purge"
		"13"		"special_bonus_unique_oracle_5"
		"14"		"special_bonus_unique_oracle_6"
		"15"		"special_bonus_unique_oracle_8"
		"16"		"special_bonus_unique_oracle_7"
		"17"		"special_bonus_unique_oracle"
		
		}
"2"
		{
			"1"		"fortunes_end"	//"oracle_fortunes_end"
		"2"		"fates_edict"//"oracle_fates_edict"
		"3"		"purifying_flames"//"oracle_purifying_flames"
		"4"		"rain_of_destiny"
		"5"		"generic_hidden"
		"6"		"false_promise"//"oracle_false_promise"
		"10"		"special_bonus_oracle_1"
		"11"		"special_bonus_oracle_2"
		"12"		"special_bonus_oracle_3"
		"13"		"special_bonus_oracle_4"
		"14"		"special_bonus_oracle_5"
		"15"		"special_bonus_unique_oracle_6"
		"16"		"special_bonus_oracle_7"
		"17"		"special_bonus_oracle_8"
		}
		
		
	}



	//=================================================================================================================
	// HERO: Underlord
	//=================================================================================================================
	"npc_dota_hero_abyssal_underlord"
	{
		
		"1"	{
            "1"		"abyssal_underlord_firestorm"
		"2"		"abyssal_underlord_pit_of_malice"
		"3"		"abyssal_underlord_atrophy_aura"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"abyssal_underlord_dark_portal"		
		"10"		"special_bonus_unique_underlord_7"
		"11"		"special_bonus_unique_underlord_8"
		"12"		"special_bonus_unique_underlord_6"
		"13"		"special_bonus_unique_underlord_5"
		"14"		"special_bonus_unique_underlord_4"
		"15"		"special_bonus_unique_underlord_3"
		"16"		"special_bonus_unique_underlord"
		"17"		"special_bonus_unique_underlord_9"
		}
"2"
		{
			"1"	"imba_abyssal_underlord_firestorm"
		"2"	"imba_abyssal_underlord_pit_of_malice"
		"3"	"imba_abyssal_underlord_atrophy_aura"
		"4"	"generic_hidden"
		"5"	"generic_hidden"
		"6"	"imba_abyssal_underlord_dark_rift"
		"10"	"special_bonus_imba_abyssal_underlord_2"
		"11"	"special_bonus_custom_value_msp30"
		"12"	"special_bonus_attack_speed_250"
		"13"	"special_bonus_imba_abyssal_underlord_4"
		"14"	"special_bonus_custom_value_ap20"
		"15"	"special_bonus_custom_value_attackrange100"
		"16"	"special_bonus_imba_abyssal_underlord_1"
		"17"	"special_bonus_imba_abyssal_underlord_3"
		"8"	""
		"9"	""
		}
		
	}

	"npc_dota_hero_monkey_king"
	{
		"1"	{"1"		"monkey_king_boundless_strike"
		"2"		"monkey_king_tree_dance"
		"3"		"monkey_king_primal_spring"
		"4"		"monkey_king_jingu_mastery"
		"5"		"monkey_king_mischief"
		"6"		"monkey_king_wukongs_command"
		"7"		"monkey_king_primal_spring_early"
		"8"		"monkey_king_untransform"
		"10"		"special_bonus_unique_monkey_king_3"
		"11"		"special_bonus_unique_monkey_king_9"
		"12"		"special_bonus_unique_monkey_king_7"
		"13"		"special_bonus_unique_monkey_king_2"
		"14"		"special_bonus_unique_monkey_king_8"
		"15"		"special_bonus_unique_monkey_king_10"
		"16"		"special_bonus_unique_monkey_king_11"
		"17"		"special_bonus_unique_monkey_king_6"
		}
"2"
		{
			"1"		"boundless_strike"	//"monkey_king_boundless_strike"
		"2"		"tree_dance"//"monkey_king_tree_dance"
		"3"		"primal_spring"			//"monkey_king_primal_spring"
		"4"		"jingu_mastery"		//"monkey_king_jingu_mastery"
		"5"		"mischief"//"monkey_king_mischief"
		"6"		"wukongs_command"//"monkey_king_wukongs_command"
	//	"7"		"monkey_king_primal_spring_early"
		"8"		"untransform"//"monkey_king_untransform"
		"10"		"special_bonus_monkey_king_1"
		"11"		"special_bonus_monkey_king_2"
		"12"		"special_bonus_monkey_king_3"
		"13"		"special_bonus_monkey_king_4"
		"14"		"special_bonus_monkey_king_5"
		"15"		"special_bonus_monkey_king_6"
		"16"		"special_bonus_monkey_king_7"
		"17"		"special_bonus_monkey_king_8"
		
	}
}

	//=================================================================================================================
	// HERO: Pangolier
	//=================================================================================================================
	"npc_dota_hero_pangolier"
	{
		
		"1"	{"1"					"pangolier_swashbuckle"
		"2"					"pangolier_shield_crash"
		"3"					"pangolier_lucky_shot"
		"4"					"pangolier_fortune_favors_the_bold"
		"5"					"pangolier_rollup"
		"6"					"pangolier_gyroshell"
		"7"					"pangolier_gyroshell_stop"
		"8"					"pangolier_rollup_stop"
		"10"					"special_bonus_unique_pangolier_luckyshot_armor"
		"11"					"special_bonus_unique_pangolier"
		"12"					"special_bonus_unique_pangolier_6"
		"13"					"special_bonus_unique_pangolier_shield_crash_herostacks"
		"14"					"special_bonus_unique_pangolier_3"
		"15"					"special_bonus_unique_pangolier_shield_crash_radius"
		"16"					"special_bonus_unique_pangolier_4"
		"17"					"special_bonus_unique_pangolier_5"
		}
"2"
		{
			"1"	"imba_pangolier_swashbuckle"
		"2"	"imba_pangolier_shield_crash"
		"3"	"imba_pangolier_lucky_shot"
		"4"	"generic_hidden"
		"5"	"generic_hidden"
		"6"	"imba_pangolier_gyroshell"
		"7"	"imba_pangolier_gyroshell_stop"
		"8"	""  

		"10"	"special_bonus_imba_pangolier_8"
		"11"	"special_bonus_imba_pangolier_7"
		"12"	"special_bonus_imba_pangolier_1"
		"13"	"special_bonus_imba_pangolier_3"
		"14"	"special_bonus_imba_pangolier_2"
		"15"	"special_bonus_imba_pangolier_4"
		"16"	"special_bonus_imba_pangolier_6"
		"17"	"special_bonus_imba_pangolier_5"

		}
		
	}

	//=================================================================================================================
	// HERO: Dark Willow
	//=================================================================================================================
	"npc_dota_hero_dark_willow"
	{
	
		"1"	{
            "1"		"dark_willow_bramble_maze"
		"2"		"dark_willow_shadow_realm"
		"3"		"dark_willow_cursed_crown"
		"4"		"dark_willow_bedlam"
		"5"		"dark_willow_pixie_dust"
		"6"		"dark_willow_terrorize"
		"10"		"special_bonus_unique_dark_willow_6"
		"11"		"special_bonus_unique_dark_willow_5"
		"12"		"special_bonus_unique_dark_willow_4"
		"13"		"special_bonus_unique_dark_willow_7"
		"14"		"special_bonus_unique_dark_willow_1"
		"15"		"special_bonus_unique_dark_willow_3"
		"16"		"special_bonus_unique_dark_willow_2"
		"17"		"special_bonus_unique_dark_willow_bedlam_targets"
		}
"2"
		{
                "1"	"imba_dark_willow_bramble_maze"
		"2"	"imba_dark_willow_shadow_realm"
		"3"	"imba_dark_willow_cursed_crown"
		"4"	"imba_dark_willow_bedlam"
		"5"	"generic_hidden"
		"6"	"imba_dark_willow_terrorize"
		"10"	"special_bonus_attack_damage_30"
		"11"	"special_bonus_cast_range_100"
		"12"	"special_bonus_gold_income_150"
		"13"	"special_bonus_movement_speed_40"
		"14"	"special_bonus_attack_speed_60"
		"15"	"special_bonus_imba_dark_willow_4"
		"16"	"special_bonus_attack_range_100"
		"17"	"special_bonus_imba_dark_willow_2"
		"7"	""
		"8"	""
		"9"	""
		}

		
	}

	//=================================================================================================================
	// HERO: Grimstroke
	//=================================================================================================================
	"npc_dota_hero_grimstroke"
	{
		
		"1"	{"1"				"grimstroke_dark_artistry"
		"2"				"grimstroke_ink_creature"
		"3"				"grimstroke_spirit_walk"
		"4"				"grimstroke_dark_portrait"
		"5"				"grimstroke_return"
		"6"				"grimstroke_soul_chain"
		"7"				"grimstroke_ink_trail"
		"10"				"special_bonus_unique_grimstroke_8"
		"11"				"special_bonus_unique_grimstroke_7"
		"12"				"special_bonus_unique_grimstroke_soul_chain_reflect_damage"
		"13"				"special_bonus_unique_grimstroke_6"
		"14"				"special_bonus_unique_grimstroke_2"
		"15"				"special_bonus_unique_grimstroke_4"
		"16"				"special_bonus_unique_grimstroke_1"
		"17"				"special_bonus_unique_grimstroke_3"
		
		}
"2"
		{

			"1"	"imba_grimstroke_dark_artistry"
		"2"	"imba_grimstroke_ink_creature"
		"3"	"imba_grimstroke_spirit_walk"
		"4"	"imba_grimstroke_dark_portrait"
		"5"	"generic_hidden"
		"6"	"imba_grimstroke_soul_chain"

		"10"	"special_bonus_imba_grimstroke_5"
		"11"	"special_bonus_imba_grimstroke_7"
		"12"	"special_bonus_imba_grimstroke_8"
		"13"	"special_bonus_imba_grimstroke_6"
		"14"	"special_bonus_imba_grimstroke_3"
		"15"	"special_bonus_imba_grimstroke_4"
		"16"	"special_bonus_imba_grimstroke_2"
		"17"	"special_bonus_imba_grimstroke_1"
		}

	
	}

	"npc_dota_hero_mars"
	{
		"1"	{
            "1"		"mars_spear"
		"2"		"mars_gods_rebuke"
		"3"		"mars_bulwark"
		"4"		"mars_dauntless"
		"5"		"generic_hidden"
		"6"		"mars_arena_of_blood"
		"10"		"special_bonus_unique_mars_rebuke_radius"
		"11"		"special_bonus_unique_mars_bulwark_redirect_chance"
		"12"		"special_bonus_unique_mars_rebuke_cooldown"
		"13"		"special_bonus_unique_mars_spear_bonus_damage"
		"14"		"special_bonus_unique_mars_bulwark_damage_reduction"
		"15"		"special_bonus_unique_mars_spear_stun_duration"
		"16"		"special_bonus_unique_mars_gods_rebuke_extra_crit"
		"17"		"special_bonus_unique_mars_arena_of_blood_hp_regen"
		}
"2"
		{
			"1"		"mars_spear"
		"2"		"dlmars_rebuke"
		"3"		"dlmars_bulwark"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"mars_arena_of_blood"
		"10"		"special_bonus_strength_20"					//10r
		"11"		"special_bonus_armor_10"					//10l
		"12"		"special_bonus_dlmars_15r"			//15r360冲击盾 距离
		"13"		"special_bonus_dlmars_15l"								//15l360度环形炖鸡
		"14"		"special_bonus_dlmars_20r"		//20r流弹附加基础力量值的纯粹伤害
		"15"		"special_bonus_dlmars_20l"		//20l+1流弹目标
		"16"		"special_bonus_attack_damage_120"	//25r
		"17"		"special_bonus_unique_mars_arena_of_blood_hp_regen"	//25l原版天赋大招回血

		"18"		"mars_bulwark"	//里技能

		"19"	"aghsfort_special_mars_spear_multiskewer"	//迷宫矛
		"20"	"aghsfort_special_mars_spear_impale_explosion"
		"21"	"aghsfort_special_mars_spear_burning_trail"

		"25" "dlmars_controller"	//控制器学习迷宫矛
		}
		
	}
	
	"npc_dota_hero_void_spirit"
	{
		
		"1"	{"1"					"void_spirit_aether_remnant"
		"2"					"void_spirit_dissimilate"
		"3"					"void_spirit_resonant_pulse"
		"4"					"void_spirit_intrinsic_edge"
		"5"					"generic_hidden"
		"6"					"void_spirit_astral_step"
		"10"					"special_bonus_mp_regen_175"
		"11"					"special_bonus_unique_void_spirit_2"
		"12"					"special_bonus_unique_void_spirit_7"
		"13"					"special_bonus_unique_void_spirit_4"
		"14"					"special_bonus_unique_void_spirit_dissimilate_outerring"
		"15"					"special_bonus_unique_void_spirit_1"
		"16"					"special_bonus_unique_void_spirit_8"
		"17"					"special_bonus_unique_void_spirit_3"
		
		}
"2"
		{
			"1"					"imba_void_spirit_aether_remnant"
		"2"					"imba_void_spirit_dissimilate"
		"3"					"imba_void_spirit_resonant_pulse"
		"4"					"imba_void_spirit_void_cut"
		"5"					"generic_hidden"
		"6"					"imba_void_spirit_astral_step"

		"10"					"special_bonus_imba_void_spirit_4"
		"11"					"special_bonus_imba_void_spirit_5"
		"12"					"special_bonus_imba_void_spirit_2"
		"13"					"special_bonus_imba_void_spirit_1"
		"14"					"special_bonus_imba_void_spirit_8"
		"15"					"special_bonus_imba_void_spirit_3"
		"16"					"special_bonus_imba_void_spirit_7"
		"17"					"special_bonus_imba_void_spirit_6"


		}

	
	}


	"npc_dota_hero_snapfire"
	{
	
		"1"	{"1"				"snapfire_scatterblast"
		"2"				"snapfire_firesnap_cookie"
		"3"				"snapfire_lil_shredder"
		"4"				"snapfire_gobble_up"
		"5"				"snapfire_spit_creep"
		"6"				"snapfire_mortimer_kisses"
		"7"				"snapfire_buckshot"
		"10"				"special_bonus_unique_snapfire_7"
		"11"				"special_bonus_unique_snapfire_5"
		"12"				"special_bonus_unique_snapfire_2"
		"13"				"special_bonus_unique_snapfire_3"
		"14"				"special_bonus_unique_snapfire_8"
		"15"				"special_bonus_unique_snapfire_mortimer_kisses_impact_damage"
		"16"				"special_bonus_unique_snapfire_6"
		"17"				"special_bonus_unique_snapfire_1"
		}
"2"
		{
			"1"	"imba_snapfire_scatterblast"
		"2"	"imba_snapfire_firesnap_cookie"
		"3"	"imba_snapfire_lil_shredder"
		"4"	"generic_hidden"
		"5"	"generic_hidden"
		"6"	"imba_snapfire_mortimer_kisses"
		
		"10"	"special_bonus_imba_snapfire_1"
		"11"	"special_bonus_imba_snapfire_7"
		"12"	"special_bonus_imba_snapfire_5"
		"13"	"special_bonus_imba_snapfire_4"
		"14"	"special_bonus_imba_snapfire_2"
		"15"	"special_bonus_imba_snapfire_3"
		"16"	"special_bonus_imba_snapfire_8"
		"17"	"special_bonus_imba_snapfire_6"
		}

		
	}

	"npc_dota_hero_hoodwink"
	{
	
		"1"	{"1"					"hoodwink_acorn_shot"
		"2"					"hoodwink_bushwhack"
		"3"					"hoodwink_scurry"
		"4"					"hoodwink_decoy"
		"5"					"hoodwink_hunters_boomerang"
		"6"					"hoodwink_mistwoods_wayfarer"
		"7"					"hoodwink_sharpshooter"
		"8"					"hoodwink_sharpshooter_release"		
		"10"					"special_bonus_unique_hoodwink_scurry_duration"
		"11"					"special_bonus_unique_hoodwink_bushwhack_cooldown"
		"12"					"special_bonus_unique_hoodwink_bushwhack_damage"
		"13"					"special_bonus_unique_hoodwink_acorn_shot_bounces"
		"14"					"special_bonus_unique_hoodwink_sharpshooter_damage"
		"15"					"special_bonus_corruption_4"
		"16"					"special_bonus_unique_hoodwink_acorn_shot_charges"
		"17"					"special_bonus_unique_hoodwink_sharpshooter_pure_damage"

		}
"2"
		{
			"1"					"imba_hoodwink_acorn_shot"
		"2"					"imba_hoodwink_bushwhack"
		"3"					"imba_hoodwink_scurry"
		"4"					"imba_hoodwink_decoy"
		"5"					"imba_hoodwink_jump"
		"6"					"imba_hoodwink_sharpshooter"
		
		"10"					"special_bonus_imba_hoodwink_7"
		"11"					"special_bonus_imba_hoodwink_2"
		"12"					"special_bonus_imba_hoodwink_1"
		"13"					"special_bonus_imba_hoodwink_4"
		"14"					"special_bonus_imba_hoodwink_5"
		"15"					"special_bonus_imba_hoodwink_6"
		"16"					"special_bonus_imba_hoodwink_3"
		"17"					"special_bonus_imba_hoodwink_8"
		}
		
	
	}

	"npc_dota_hero_dawnbreaker"
	{
		
		"1"	{"1"		"dawnbreaker_fire_wreath"
		"2"		"dawnbreaker_celestial_hammer"
		"3"		"dawnbreaker_luminosity"
		"4"		"dawnbreaker_converge"
		"5"		"dawnbreaker_break_of_dawn"
		"6"		"dawnbreaker_solar_guardian"
		"7"		"dawnbreaker_land"
		"10"		"special_bonus_unique_dawnbreaker_fire_wreath_swipe"
		"11"		"special_bonus_unique_dawnbreaker_celestial_hammer_slow"
		"12"		"special_bonus_unique_dawnbreaker_luminosity_crit"
		"13"		"special_bonus_unique_dawnbreaker_solar_guardian_cooldown"
		"14"		"special_bonus_unique_dawnbreaker_solar_guardian_radius"
		"15"		"special_bonus_unique_dawnbreaker_luminosity_attack_count"
		"16"		"special_bonus_unique_dawnbreaker_fire_wreath_cooldown"
		"17"		"special_bonus_unique_dawnbreaker_celestial_hammer_cast_range"
		
		}
"2"
		{
			"1"		"imba_dawnbreaker_fire_wreath"
		"2"		"imba_dawnbreaker_celestial_hammer"
		"3"		"imba_dawnbreaker_luminosity"
		"4"		"generic_hidden"
		"5"		"generic_hidden"
		"6"		"imba_dawnbreaker_solar_guardian"

		"10"	"special_bonus_imba_dawnbreaker_2"
		"11"	"special_bonus_imba_dawnbreaker_4"
		"12"	"special_bonus_imba_dawnbreaker_1"
		"13"	"special_bonus_imba_dawnbreaker_6"
		"14"	"special_bonus_imba_dawnbreaker_7"
		"15"	"special_bonus_imba_dawnbreaker_8"
		"16"	"special_bonus_imba_dawnbreaker_5"
		"17"	"special_bonus_imba_dawnbreaker_3"
		}

	
	}
	"npc_dota_hero_marci"
	{
	
		"1"	{"1"		"marci_grapple"
		"2"		"marci_companion_run"
		"3"		"generic_hidden"
		"4"		"marci_special_delivery"
		"5"		"generic_hidden"
		"6"		"marci_unleash"
		"10"		"special_bonus_unique_marci_lunge_range"
		"11"		"special_bonus_unique_marci_guardian_lifesteal"
		"12"		"special_bonus_unique_marci_grapple_damage"
		"13"		"special_bonus_unique_marci_lunge_movespeed"
		"14"		"special_bonus_unique_marci_grapple_stun_duration"
		"15"		"special_bonus_unique_marci_unleash_speed"
		"16"		"special_bonus_unique_marci_unleash_extend_duration"
		"17"		"special_bonus_unique_marci_guardian_damage"
		}
"2"
		{
			"1"		"imba_marci_grapple"
		"2"		"imba_marci_companion_run"
		"3"		"imba_marci_guardian"
		"4"		"imba_marci_swing"
		"5"		"generic_hidden"
		"6"		"imba_marci_unleash"

		"10"	"special_bonus_imba_marci_8"
		"11"	"special_bonus_imba_marci_1"
		"12"	"special_bonus_imba_marci_4"
		"13"	"special_bonus_imba_marci_7"
		"14"	"special_bonus_imba_marci_2"
		"15"	"special_bonus_imba_marci_5"
		"16"	"special_bonus_imba_marci_3"
		"17"	"special_bonus_imba_marci_6"
	}

		}
	
	"npc_dota_hero_primal_beast"
	{
	
		"1"	{
            "1"				"primal_beast_onslaught"
		"2"				"primal_beast_trample"
		"3"				"primal_beast_uproar"
		"4"				"primal_beast_rock_throw"
		"5"				"primal_beast_onslaught_release"
		"6"				"primal_beast_pulverize"
		"7"				"primal_beast_colossal"
		"10"				"special_bonus_unique_primal_beast_onslaught_damage"
		"11"				"special_bonus_unique_primal_beast_trample_magic_resist"
		"12"				"special_bonus_unique_primal_beast_trample_cooldown"
		"13"				"special_bonus_unique_primal_beast_roar_dispells"
		"14"				"special_bonus_unique_primal_beast_trample_attack_damage"
		"15"				"special_bonus_unique_primal_beast_uproar_armor"
		"16"				"special_bonus_unique_primal_beast_trample_unslowable"
		"17"				"special_bonus_unique_primal_beast_pulverize_duration"
		
		}
"2"
		{
			"1"				"imba_onslaught"
		"2"				"imba_trample"
		"3"				"imba_uproar"
		"6"		        "imba_pulverize"
		"4"				"primal_beast_rock_throw"
		"5"		        "generic_hidden"
		"8"		        "imba_onslaught_again"
		"10"				"special_bonus_custom_value_msp30"
		"11"				"special_bonus_unique_primal_beast_onslaught_charges"
		"12"				"special_bonus_unique_imba_primal_beast_3"
		"13"				"special_bonus_unique_primal_beast_onslaught_damage"
		"14"				"special_bonus_unique_primal_beast_trample_attack_damage"
		"15"				"special_bonus_imba_primal_beast_7"
		//"15"			"special_bonus_unique_primal_beast_roar_dispells"
		"16"				"special_bonus_imba_primal_beast_6"
		"17"				"special_bonus_spell_lifesteal_50"
		
		}

	}	  
}