print("进入 activate_entry.lua")

-- 只在 Activate 之后执行
require("tools/keyvalues")
require("tools/timers")
require("tools/animations")
require("tools/notifications")
require("tools/physics")
require("tools/pseudorandom")
require("tools/abilitychargecontroller")
require("events/events")
require("events/custom_events")
require("bots/bot_config")
require("building")
require("player")
require("unit")
require("wearable")
require("modifier/veteran_talent/veteran_talent_contral")
require("spawner_creep")
require("ai/poor_ai_core")
require("ai/ai_normal")
require("game")

GameRules.L_TG = L_TG()
GameRules.L_TG:InitGameMode()