require("tools/debug_utils")
require('tools/client_utils')
require('precache')
require('modifier/veteran_talent/veteran_talent_contral')
--require("mob_spawner")
require('spawner_creep')
require('ai/poor_ai_core')
require('ai/ai_normal')
require('tools/abilitychargecontroller')

AbilityKV = LoadKeyValues("scripts/npc/npc_abilities_custom.txt")
HEROSKV = LoadKeyValues("scripts/npc/herolist.txt")
HeroTalent = LoadKeyValues("scripts/npc/kv/talent.kv")
HEROSK = LoadKeyValues("scripts/npc/kv/hero_sk.kv")
Awake()